// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auths.proto

#ifndef PROTOBUF_auths_2eproto__INCLUDED
#define PROTOBUF_auths_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_auths_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsUserTokenAuthReqImpl();
void InitDefaultsUserTokenAuthReq();
void InitDefaultsUserTokenAuthRspImpl();
void InitDefaultsUserTokenAuthRsp();
inline void InitDefaults() {
  InitDefaultsUserTokenAuthReq();
  InitDefaultsUserTokenAuthRsp();
}
}  // namespace protobuf_auths_2eproto
namespace zproto {
class UserTokenAuthReq;
class UserTokenAuthReqDefaultTypeInternal;
extern UserTokenAuthReqDefaultTypeInternal _UserTokenAuthReq_default_instance_;
class UserTokenAuthRsp;
class UserTokenAuthRspDefaultTypeInternal;
extern UserTokenAuthRspDefaultTypeInternal _UserTokenAuthRsp_default_instance_;
}  // namespace zproto
namespace zproto {

// ===================================================================

class UserTokenAuthReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.UserTokenAuthReq) */ {
 public:
  UserTokenAuthReq();
  virtual ~UserTokenAuthReq();

  UserTokenAuthReq(const UserTokenAuthReq& from);

  inline UserTokenAuthReq& operator=(const UserTokenAuthReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserTokenAuthReq(UserTokenAuthReq&& from) noexcept
    : UserTokenAuthReq() {
    *this = ::std::move(from);
  }

  inline UserTokenAuthReq& operator=(UserTokenAuthReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserTokenAuthReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserTokenAuthReq* internal_default_instance() {
    return reinterpret_cast<const UserTokenAuthReq*>(
               &_UserTokenAuthReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(UserTokenAuthReq* other);
  friend void swap(UserTokenAuthReq& a, UserTokenAuthReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserTokenAuthReq* New() const PROTOBUF_FINAL { return New(NULL); }

  UserTokenAuthReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserTokenAuthReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string app_key = 1;
  void clear_app_key();
  static const int kAppKeyFieldNumber = 1;
  const ::std::string& app_key() const;
  void set_app_key(const ::std::string& value);
  #if LANG_CXX11
  void set_app_key(::std::string&& value);
  #endif
  void set_app_key(const char* value);
  void set_app_key(const char* value, size_t size);
  ::std::string* mutable_app_key();
  ::std::string* release_app_key();
  void set_allocated_app_key(::std::string* app_key);

  // string user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  #if LANG_CXX11
  void set_user_id(::std::string&& value);
  #endif
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // string user_token = 3;
  void clear_user_token();
  static const int kUserTokenFieldNumber = 3;
  const ::std::string& user_token() const;
  void set_user_token(const ::std::string& value);
  #if LANG_CXX11
  void set_user_token(::std::string&& value);
  #endif
  void set_user_token(const char* value);
  void set_user_token(const char* value, size_t size);
  ::std::string* mutable_user_token();
  ::std::string* release_user_token();
  void set_allocated_user_token(::std::string* user_token);

  // @@protoc_insertion_point(class_scope:zproto.UserTokenAuthReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr app_key_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::google::protobuf::internal::ArenaStringPtr user_token_;
  mutable int _cached_size_;
  friend struct ::protobuf_auths_2eproto::TableStruct;
  friend void ::protobuf_auths_2eproto::InitDefaultsUserTokenAuthReqImpl();
};
// -------------------------------------------------------------------

class UserTokenAuthRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.UserTokenAuthRsp) */ {
 public:
  UserTokenAuthRsp();
  virtual ~UserTokenAuthRsp();

  UserTokenAuthRsp(const UserTokenAuthRsp& from);

  inline UserTokenAuthRsp& operator=(const UserTokenAuthRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserTokenAuthRsp(UserTokenAuthRsp&& from) noexcept
    : UserTokenAuthRsp() {
    *this = ::std::move(from);
  }

  inline UserTokenAuthRsp& operator=(UserTokenAuthRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserTokenAuthRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserTokenAuthRsp* internal_default_instance() {
    return reinterpret_cast<const UserTokenAuthRsp*>(
               &_UserTokenAuthRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(UserTokenAuthRsp* other);
  friend void swap(UserTokenAuthRsp& a, UserTokenAuthRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserTokenAuthRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  UserTokenAuthRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserTokenAuthRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string user_id = 2;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  const ::std::string& user_id() const;
  void set_user_id(const ::std::string& value);
  #if LANG_CXX11
  void set_user_id(::std::string&& value);
  #endif
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  ::std::string* mutable_user_id();
  ::std::string* release_user_id();
  void set_allocated_user_id(::std::string* user_id);

  // string nick = 3;
  void clear_nick();
  static const int kNickFieldNumber = 3;
  const ::std::string& nick() const;
  void set_nick(const ::std::string& value);
  #if LANG_CXX11
  void set_nick(::std::string&& value);
  #endif
  void set_nick(const char* value);
  void set_nick(const char* value, size_t size);
  ::std::string* mutable_nick();
  ::std::string* release_nick();
  void set_allocated_nick(::std::string* nick);

  // string avatar = 4;
  void clear_avatar();
  static const int kAvatarFieldNumber = 4;
  const ::std::string& avatar() const;
  void set_avatar(const ::std::string& value);
  #if LANG_CXX11
  void set_avatar(::std::string&& value);
  #endif
  void set_avatar(const char* value);
  void set_avatar(const char* value, size_t size);
  ::std::string* mutable_avatar();
  ::std::string* release_avatar();
  void set_allocated_avatar(::std::string* avatar);

  // uint32 app_id = 1;
  void clear_app_id();
  static const int kAppIdFieldNumber = 1;
  ::google::protobuf::uint32 app_id() const;
  void set_app_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:zproto.UserTokenAuthRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr user_id_;
  ::google::protobuf::internal::ArenaStringPtr nick_;
  ::google::protobuf::internal::ArenaStringPtr avatar_;
  ::google::protobuf::uint32 app_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_auths_2eproto::TableStruct;
  friend void ::protobuf_auths_2eproto::InitDefaultsUserTokenAuthRspImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// UserTokenAuthReq

// string app_key = 1;
inline void UserTokenAuthReq::clear_app_key() {
  app_key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserTokenAuthReq::app_key() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthReq.app_key)
  return app_key_.GetNoArena();
}
inline void UserTokenAuthReq::set_app_key(const ::std::string& value) {
  
  app_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthReq.app_key)
}
#if LANG_CXX11
inline void UserTokenAuthReq::set_app_key(::std::string&& value) {
  
  app_key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserTokenAuthReq.app_key)
}
#endif
inline void UserTokenAuthReq::set_app_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  app_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserTokenAuthReq.app_key)
}
inline void UserTokenAuthReq::set_app_key(const char* value, size_t size) {
  
  app_key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserTokenAuthReq.app_key)
}
inline ::std::string* UserTokenAuthReq::mutable_app_key() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserTokenAuthReq.app_key)
  return app_key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserTokenAuthReq::release_app_key() {
  // @@protoc_insertion_point(field_release:zproto.UserTokenAuthReq.app_key)
  
  return app_key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserTokenAuthReq::set_allocated_app_key(::std::string* app_key) {
  if (app_key != NULL) {
    
  } else {
    
  }
  app_key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), app_key);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserTokenAuthReq.app_key)
}

// string user_id = 2;
inline void UserTokenAuthReq::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserTokenAuthReq::user_id() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthReq.user_id)
  return user_id_.GetNoArena();
}
inline void UserTokenAuthReq::set_user_id(const ::std::string& value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthReq.user_id)
}
#if LANG_CXX11
inline void UserTokenAuthReq::set_user_id(::std::string&& value) {
  
  user_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserTokenAuthReq.user_id)
}
#endif
inline void UserTokenAuthReq::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserTokenAuthReq.user_id)
}
inline void UserTokenAuthReq::set_user_id(const char* value, size_t size) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserTokenAuthReq.user_id)
}
inline ::std::string* UserTokenAuthReq::mutable_user_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserTokenAuthReq.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserTokenAuthReq::release_user_id() {
  // @@protoc_insertion_point(field_release:zproto.UserTokenAuthReq.user_id)
  
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserTokenAuthReq::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    
  } else {
    
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserTokenAuthReq.user_id)
}

// string user_token = 3;
inline void UserTokenAuthReq::clear_user_token() {
  user_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserTokenAuthReq::user_token() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthReq.user_token)
  return user_token_.GetNoArena();
}
inline void UserTokenAuthReq::set_user_token(const ::std::string& value) {
  
  user_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthReq.user_token)
}
#if LANG_CXX11
inline void UserTokenAuthReq::set_user_token(::std::string&& value) {
  
  user_token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserTokenAuthReq.user_token)
}
#endif
inline void UserTokenAuthReq::set_user_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserTokenAuthReq.user_token)
}
inline void UserTokenAuthReq::set_user_token(const char* value, size_t size) {
  
  user_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserTokenAuthReq.user_token)
}
inline ::std::string* UserTokenAuthReq::mutable_user_token() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserTokenAuthReq.user_token)
  return user_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserTokenAuthReq::release_user_token() {
  // @@protoc_insertion_point(field_release:zproto.UserTokenAuthReq.user_token)
  
  return user_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserTokenAuthReq::set_allocated_user_token(::std::string* user_token) {
  if (user_token != NULL) {
    
  } else {
    
  }
  user_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_token);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserTokenAuthReq.user_token)
}

// -------------------------------------------------------------------

// UserTokenAuthRsp

// uint32 app_id = 1;
inline void UserTokenAuthRsp::clear_app_id() {
  app_id_ = 0u;
}
inline ::google::protobuf::uint32 UserTokenAuthRsp::app_id() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthRsp.app_id)
  return app_id_;
}
inline void UserTokenAuthRsp::set_app_id(::google::protobuf::uint32 value) {
  
  app_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthRsp.app_id)
}

// string user_id = 2;
inline void UserTokenAuthRsp::clear_user_id() {
  user_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserTokenAuthRsp::user_id() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthRsp.user_id)
  return user_id_.GetNoArena();
}
inline void UserTokenAuthRsp::set_user_id(const ::std::string& value) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthRsp.user_id)
}
#if LANG_CXX11
inline void UserTokenAuthRsp::set_user_id(::std::string&& value) {
  
  user_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserTokenAuthRsp.user_id)
}
#endif
inline void UserTokenAuthRsp::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserTokenAuthRsp.user_id)
}
inline void UserTokenAuthRsp::set_user_id(const char* value, size_t size) {
  
  user_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserTokenAuthRsp.user_id)
}
inline ::std::string* UserTokenAuthRsp::mutable_user_id() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserTokenAuthRsp.user_id)
  return user_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserTokenAuthRsp::release_user_id() {
  // @@protoc_insertion_point(field_release:zproto.UserTokenAuthRsp.user_id)
  
  return user_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserTokenAuthRsp::set_allocated_user_id(::std::string* user_id) {
  if (user_id != NULL) {
    
  } else {
    
  }
  user_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_id);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserTokenAuthRsp.user_id)
}

// string nick = 3;
inline void UserTokenAuthRsp::clear_nick() {
  nick_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserTokenAuthRsp::nick() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthRsp.nick)
  return nick_.GetNoArena();
}
inline void UserTokenAuthRsp::set_nick(const ::std::string& value) {
  
  nick_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthRsp.nick)
}
#if LANG_CXX11
inline void UserTokenAuthRsp::set_nick(::std::string&& value) {
  
  nick_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserTokenAuthRsp.nick)
}
#endif
inline void UserTokenAuthRsp::set_nick(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  nick_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserTokenAuthRsp.nick)
}
inline void UserTokenAuthRsp::set_nick(const char* value, size_t size) {
  
  nick_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserTokenAuthRsp.nick)
}
inline ::std::string* UserTokenAuthRsp::mutable_nick() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserTokenAuthRsp.nick)
  return nick_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserTokenAuthRsp::release_nick() {
  // @@protoc_insertion_point(field_release:zproto.UserTokenAuthRsp.nick)
  
  return nick_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserTokenAuthRsp::set_allocated_nick(::std::string* nick) {
  if (nick != NULL) {
    
  } else {
    
  }
  nick_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nick);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserTokenAuthRsp.nick)
}

// string avatar = 4;
inline void UserTokenAuthRsp::clear_avatar() {
  avatar_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserTokenAuthRsp::avatar() const {
  // @@protoc_insertion_point(field_get:zproto.UserTokenAuthRsp.avatar)
  return avatar_.GetNoArena();
}
inline void UserTokenAuthRsp::set_avatar(const ::std::string& value) {
  
  avatar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserTokenAuthRsp.avatar)
}
#if LANG_CXX11
inline void UserTokenAuthRsp::set_avatar(::std::string&& value) {
  
  avatar_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserTokenAuthRsp.avatar)
}
#endif
inline void UserTokenAuthRsp::set_avatar(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  avatar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserTokenAuthRsp.avatar)
}
inline void UserTokenAuthRsp::set_avatar(const char* value, size_t size) {
  
  avatar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserTokenAuthRsp.avatar)
}
inline ::std::string* UserTokenAuthRsp::mutable_avatar() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserTokenAuthRsp.avatar)
  return avatar_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserTokenAuthRsp::release_avatar() {
  // @@protoc_insertion_point(field_release:zproto.UserTokenAuthRsp.avatar)
  
  return avatar_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserTokenAuthRsp::set_allocated_avatar(::std::string* avatar) {
  if (avatar != NULL) {
    
  } else {
    
  }
  avatar_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), avatar);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserTokenAuthRsp.avatar)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_auths_2eproto__INCLUDED
