// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: presences.proto

#include "presences.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace zproto {
class ZUserIDDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ZUserID>
      _instance;
} _ZUserID_default_instance_;
class ZOnlineUserDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ZOnlineUser>
      _instance;
} _ZOnlineUser_default_instance_;
class ClientOnlineReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientOnlineReq>
      _instance;
} _ClientOnlineReq_default_instance_;
class ClientOnlineRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientOnlineRsp>
      _instance;
} _ClientOnlineRsp_default_instance_;
class ClientOfflineReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientOfflineReq>
      _instance;
} _ClientOfflineReq_default_instance_;
class ClientOfflineRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientOfflineRsp>
      _instance;
} _ClientOfflineRsp_default_instance_;
class QueryOnlineUserReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<QueryOnlineUserReq>
      _instance;
} _QueryOnlineUserReq_default_instance_;
class QueryOnlineUserRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<QueryOnlineUserRsp>
      _instance;
} _QueryOnlineUserRsp_default_instance_;
}  // namespace zproto
namespace protobuf_presences_2eproto {
void InitDefaultsZUserIDImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ZUserID_default_instance_;
    new (ptr) ::zproto::ZUserID();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ZUserID::InitAsDefaultInstance();
}

void InitDefaultsZUserID() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsZUserIDImpl);
}

void InitDefaultsZOnlineUserImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ZOnlineUser_default_instance_;
    new (ptr) ::zproto::ZOnlineUser();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ZOnlineUser::InitAsDefaultInstance();
}

void InitDefaultsZOnlineUser() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsZOnlineUserImpl);
}

void InitDefaultsClientOnlineReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ClientOnlineReq_default_instance_;
    new (ptr) ::zproto::ClientOnlineReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ClientOnlineReq::InitAsDefaultInstance();
}

void InitDefaultsClientOnlineReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsClientOnlineReqImpl);
}

void InitDefaultsClientOnlineRspImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ClientOnlineRsp_default_instance_;
    new (ptr) ::zproto::ClientOnlineRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ClientOnlineRsp::InitAsDefaultInstance();
}

void InitDefaultsClientOnlineRsp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsClientOnlineRspImpl);
}

void InitDefaultsClientOfflineReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ClientOfflineReq_default_instance_;
    new (ptr) ::zproto::ClientOfflineReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ClientOfflineReq::InitAsDefaultInstance();
}

void InitDefaultsClientOfflineReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsClientOfflineReqImpl);
}

void InitDefaultsClientOfflineRspImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ClientOfflineRsp_default_instance_;
    new (ptr) ::zproto::ClientOfflineRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ClientOfflineRsp::InitAsDefaultInstance();
}

void InitDefaultsClientOfflineRsp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsClientOfflineRspImpl);
}

void InitDefaultsQueryOnlineUserReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_presences_2eproto::InitDefaultsZUserID();
  {
    void* ptr = &::zproto::_QueryOnlineUserReq_default_instance_;
    new (ptr) ::zproto::QueryOnlineUserReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::QueryOnlineUserReq::InitAsDefaultInstance();
}

void InitDefaultsQueryOnlineUserReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsQueryOnlineUserReqImpl);
}

void InitDefaultsQueryOnlineUserRspImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_presences_2eproto::InitDefaultsZOnlineUser();
  {
    void* ptr = &::zproto::_QueryOnlineUserRsp_default_instance_;
    new (ptr) ::zproto::QueryOnlineUserRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::QueryOnlineUserRsp::InitAsDefaultInstance();
}

void InitDefaultsQueryOnlineUserRsp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsQueryOnlineUserRspImpl);
}

::google::protobuf::Metadata file_level_metadata[8];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZUserID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZUserID, app_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZUserID, user_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZOnlineUser, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZOnlineUser, app_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZOnlineUser, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZOnlineUser, server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ZOnlineUser, conn_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineReq, server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineReq, conn_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineReq, app_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineReq, user_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineReq, state_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOnlineRsp, index_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOfflineReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOfflineReq, server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOfflineReq, conn_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOfflineRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ClientOfflineRsp, index_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::QueryOnlineUserReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::QueryOnlineUserReq, user_id_list_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::QueryOnlineUserRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::QueryOnlineUserRsp, online_users_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::zproto::ZUserID)},
  { 7, -1, sizeof(::zproto::ZOnlineUser)},
  { 16, -1, sizeof(::zproto::ClientOnlineReq)},
  { 26, -1, sizeof(::zproto::ClientOnlineRsp)},
  { 32, -1, sizeof(::zproto::ClientOfflineReq)},
  { 39, -1, sizeof(::zproto::ClientOfflineRsp)},
  { 45, -1, sizeof(::zproto::QueryOnlineUserReq)},
  { 51, -1, sizeof(::zproto::QueryOnlineUserRsp)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ZUserID_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ZOnlineUser_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ClientOnlineReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ClientOnlineRsp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ClientOfflineReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ClientOfflineRsp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_QueryOnlineUserReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_QueryOnlineUserRsp_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "presences.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 8);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017presences.proto\022\006zproto\"*\n\007ZUserID\022\016\n\006"
      "app_id\030\001 \001(\r\022\017\n\007user_id\030\002 \001(\t\"R\n\013ZOnline"
      "User\022\016\n\006app_id\030\001 \001(\r\022\017\n\007user_id\030\002 \001(\t\022\021\n"
      "\tserver_id\030\003 \001(\r\022\017\n\007conn_id\030\004 \001(\004\"e\n\017Cli"
      "entOnlineReq\022\021\n\tserver_id\030\001 \001(\r\022\017\n\007conn_"
      "id\030\002 \001(\004\022\016\n\006app_id\030\003 \001(\r\022\017\n\007user_id\030\004 \001("
      "\t\022\r\n\005state\030\005 \001(\r\"#\n\017ClientOnlineRsp\022\020\n\010i"
      "ndex_id\030\001 \001(\004\"6\n\020ClientOfflineReq\022\021\n\tser"
      "ver_id\030\001 \001(\r\022\017\n\007conn_id\030\002 \001(\004\"$\n\020ClientO"
      "fflineRsp\022\020\n\010index_id\030\001 \001(\004\";\n\022QueryOnli"
      "neUserReq\022%\n\014user_id_list\030\001 \003(\0132\017.zproto"
      ".ZUserID\"\?\n\022QueryOnlineUserRsp\022)\n\014online"
      "_users\030\001 \003(\0132\023.zproto.ZOnlineUserB,\n\027com"
      ".zchat.engine.zprotoB\017ZProtoPresencesH\002b"
      "\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 567);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "presences.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_presences_2eproto
namespace zproto {

// ===================================================================

void ZUserID::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZUserID::kAppIdFieldNumber;
const int ZUserID::kUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZUserID::ZUserID()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsZUserID();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ZUserID)
}
ZUserID::ZUserID(const ZUserID& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.user_id().size() > 0) {
    user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
  }
  app_id_ = from.app_id_;
  // @@protoc_insertion_point(copy_constructor:zproto.ZUserID)
}

void ZUserID::SharedCtor() {
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  app_id_ = 0u;
  _cached_size_ = 0;
}

ZUserID::~ZUserID() {
  // @@protoc_insertion_point(destructor:zproto.ZUserID)
  SharedDtor();
}

void ZUserID::SharedDtor() {
  user_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ZUserID::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZUserID::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ZUserID& ZUserID::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsZUserID();
  return *internal_default_instance();
}

ZUserID* ZUserID::New(::google::protobuf::Arena* arena) const {
  ZUserID* n = new ZUserID;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZUserID::Swap(ZUserID* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZUserID::InternalSwap(ZUserID* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ZUserID::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ZOnlineUser::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ZOnlineUser::kAppIdFieldNumber;
const int ZOnlineUser::kUserIdFieldNumber;
const int ZOnlineUser::kServerIdFieldNumber;
const int ZOnlineUser::kConnIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ZOnlineUser::ZOnlineUser()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsZOnlineUser();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ZOnlineUser)
}
ZOnlineUser::ZOnlineUser(const ZOnlineUser& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.user_id().size() > 0) {
    user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
  }
  ::memcpy(&app_id_, &from.app_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&conn_id_) -
    reinterpret_cast<char*>(&app_id_)) + sizeof(conn_id_));
  // @@protoc_insertion_point(copy_constructor:zproto.ZOnlineUser)
}

void ZOnlineUser::SharedCtor() {
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&conn_id_) -
      reinterpret_cast<char*>(&app_id_)) + sizeof(conn_id_));
  _cached_size_ = 0;
}

ZOnlineUser::~ZOnlineUser() {
  // @@protoc_insertion_point(destructor:zproto.ZOnlineUser)
  SharedDtor();
}

void ZOnlineUser::SharedDtor() {
  user_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ZOnlineUser::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ZOnlineUser::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ZOnlineUser& ZOnlineUser::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsZOnlineUser();
  return *internal_default_instance();
}

ZOnlineUser* ZOnlineUser::New(::google::protobuf::Arena* arena) const {
  ZOnlineUser* n = new ZOnlineUser;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ZOnlineUser::Swap(ZOnlineUser* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ZOnlineUser::InternalSwap(ZOnlineUser* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ZOnlineUser::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ClientOnlineReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOnlineReq::kServerIdFieldNumber;
const int ClientOnlineReq::kConnIdFieldNumber;
const int ClientOnlineReq::kAppIdFieldNumber;
const int ClientOnlineReq::kUserIdFieldNumber;
const int ClientOnlineReq::kStateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOnlineReq::ClientOnlineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsClientOnlineReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOnlineReq)
}
ClientOnlineReq::ClientOnlineReq(const ClientOnlineReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.user_id().size() > 0) {
    user_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.user_id_);
  }
  ::memcpy(&conn_id_, &from.conn_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&state_) -
    reinterpret_cast<char*>(&conn_id_)) + sizeof(state_));
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOnlineReq)
}

void ClientOnlineReq::SharedCtor() {
  user_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&conn_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&conn_id_)) + sizeof(state_));
  _cached_size_ = 0;
}

ClientOnlineReq::~ClientOnlineReq() {
  // @@protoc_insertion_point(destructor:zproto.ClientOnlineReq)
  SharedDtor();
}

void ClientOnlineReq::SharedDtor() {
  user_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ClientOnlineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOnlineReq::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientOnlineReq& ClientOnlineReq::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsClientOnlineReq();
  return *internal_default_instance();
}

ClientOnlineReq* ClientOnlineReq::New(::google::protobuf::Arena* arena) const {
  ClientOnlineReq* n = new ClientOnlineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOnlineReq::Swap(ClientOnlineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOnlineReq::InternalSwap(ClientOnlineReq* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOnlineReq::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ClientOnlineRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOnlineRsp::kIndexIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOnlineRsp::ClientOnlineRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsClientOnlineRsp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOnlineRsp)
}
ClientOnlineRsp::ClientOnlineRsp(const ClientOnlineRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  index_id_ = from.index_id_;
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOnlineRsp)
}

void ClientOnlineRsp::SharedCtor() {
  index_id_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

ClientOnlineRsp::~ClientOnlineRsp() {
  // @@protoc_insertion_point(destructor:zproto.ClientOnlineRsp)
  SharedDtor();
}

void ClientOnlineRsp::SharedDtor() {
}

void ClientOnlineRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOnlineRsp::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientOnlineRsp& ClientOnlineRsp::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsClientOnlineRsp();
  return *internal_default_instance();
}

ClientOnlineRsp* ClientOnlineRsp::New(::google::protobuf::Arena* arena) const {
  ClientOnlineRsp* n = new ClientOnlineRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOnlineRsp::Swap(ClientOnlineRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOnlineRsp::InternalSwap(ClientOnlineRsp* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOnlineRsp::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ClientOfflineReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOfflineReq::kServerIdFieldNumber;
const int ClientOfflineReq::kConnIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOfflineReq::ClientOfflineReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsClientOfflineReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOfflineReq)
}
ClientOfflineReq::ClientOfflineReq(const ClientOfflineReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&conn_id_, &from.conn_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&server_id_) -
    reinterpret_cast<char*>(&conn_id_)) + sizeof(server_id_));
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOfflineReq)
}

void ClientOfflineReq::SharedCtor() {
  ::memset(&conn_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&server_id_) -
      reinterpret_cast<char*>(&conn_id_)) + sizeof(server_id_));
  _cached_size_ = 0;
}

ClientOfflineReq::~ClientOfflineReq() {
  // @@protoc_insertion_point(destructor:zproto.ClientOfflineReq)
  SharedDtor();
}

void ClientOfflineReq::SharedDtor() {
}

void ClientOfflineReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOfflineReq::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientOfflineReq& ClientOfflineReq::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsClientOfflineReq();
  return *internal_default_instance();
}

ClientOfflineReq* ClientOfflineReq::New(::google::protobuf::Arena* arena) const {
  ClientOfflineReq* n = new ClientOfflineReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOfflineReq::Swap(ClientOfflineReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOfflineReq::InternalSwap(ClientOfflineReq* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOfflineReq::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ClientOfflineRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientOfflineRsp::kIndexIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientOfflineRsp::ClientOfflineRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsClientOfflineRsp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ClientOfflineRsp)
}
ClientOfflineRsp::ClientOfflineRsp(const ClientOfflineRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  index_id_ = from.index_id_;
  // @@protoc_insertion_point(copy_constructor:zproto.ClientOfflineRsp)
}

void ClientOfflineRsp::SharedCtor() {
  index_id_ = GOOGLE_ULONGLONG(0);
  _cached_size_ = 0;
}

ClientOfflineRsp::~ClientOfflineRsp() {
  // @@protoc_insertion_point(destructor:zproto.ClientOfflineRsp)
  SharedDtor();
}

void ClientOfflineRsp::SharedDtor() {
}

void ClientOfflineRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientOfflineRsp::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientOfflineRsp& ClientOfflineRsp::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsClientOfflineRsp();
  return *internal_default_instance();
}

ClientOfflineRsp* ClientOfflineRsp::New(::google::protobuf::Arena* arena) const {
  ClientOfflineRsp* n = new ClientOfflineRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientOfflineRsp::Swap(ClientOfflineRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientOfflineRsp::InternalSwap(ClientOfflineRsp* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ClientOfflineRsp::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void QueryOnlineUserReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int QueryOnlineUserReq::kUserIdListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

QueryOnlineUserReq::QueryOnlineUserReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsQueryOnlineUserReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.QueryOnlineUserReq)
}
QueryOnlineUserReq::QueryOnlineUserReq(const QueryOnlineUserReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      user_id_list_(from.user_id_list_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:zproto.QueryOnlineUserReq)
}

void QueryOnlineUserReq::SharedCtor() {
  _cached_size_ = 0;
}

QueryOnlineUserReq::~QueryOnlineUserReq() {
  // @@protoc_insertion_point(destructor:zproto.QueryOnlineUserReq)
  SharedDtor();
}

void QueryOnlineUserReq::SharedDtor() {
}

void QueryOnlineUserReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QueryOnlineUserReq::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const QueryOnlineUserReq& QueryOnlineUserReq::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsQueryOnlineUserReq();
  return *internal_default_instance();
}

QueryOnlineUserReq* QueryOnlineUserReq::New(::google::protobuf::Arena* arena) const {
  QueryOnlineUserReq* n = new QueryOnlineUserReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void QueryOnlineUserReq::Swap(QueryOnlineUserReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void QueryOnlineUserReq::InternalSwap(QueryOnlineUserReq* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata QueryOnlineUserReq::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void QueryOnlineUserRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int QueryOnlineUserRsp::kOnlineUsersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

QueryOnlineUserRsp::QueryOnlineUserRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_presences_2eproto::InitDefaultsQueryOnlineUserRsp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.QueryOnlineUserRsp)
}
QueryOnlineUserRsp::QueryOnlineUserRsp(const QueryOnlineUserRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      online_users_(from.online_users_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:zproto.QueryOnlineUserRsp)
}

void QueryOnlineUserRsp::SharedCtor() {
  _cached_size_ = 0;
}

QueryOnlineUserRsp::~QueryOnlineUserRsp() {
  // @@protoc_insertion_point(destructor:zproto.QueryOnlineUserRsp)
  SharedDtor();
}

void QueryOnlineUserRsp::SharedDtor() {
}

void QueryOnlineUserRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* QueryOnlineUserRsp::descriptor() {
  ::protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const QueryOnlineUserRsp& QueryOnlineUserRsp::default_instance() {
  ::protobuf_presences_2eproto::InitDefaultsQueryOnlineUserRsp();
  return *internal_default_instance();
}

QueryOnlineUserRsp* QueryOnlineUserRsp::New(::google::protobuf::Arena* arena) const {
  QueryOnlineUserRsp* n = new QueryOnlineUserRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void QueryOnlineUserRsp::Swap(QueryOnlineUserRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void QueryOnlineUserRsp::InternalSwap(QueryOnlineUserRsp* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata QueryOnlineUserRsp::GetMetadata() const {
  protobuf_presences_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_presences_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace zproto

// @@protoc_insertion_point(global_scope)
