// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servers.proto

#include "servers.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace zproto {
class ServerAuthReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerAuthReq>
      _instance;
} _ServerAuthReq_default_instance_;
class ServerAuthRspDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerAuthRsp>
      _instance;
} _ServerAuthRsp_default_instance_;
class DeliveryDataToUsersReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DeliveryDataToUsersReq>
      _instance;
} _DeliveryDataToUsersReq_default_instance_;
}  // namespace zproto
namespace protobuf_servers_2eproto {
void InitDefaultsServerAuthReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ServerAuthReq_default_instance_;
    new (ptr) ::zproto::ServerAuthReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ServerAuthReq::InitAsDefaultInstance();
}

void InitDefaultsServerAuthReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsServerAuthReqImpl);
}

void InitDefaultsServerAuthRspImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_ServerAuthRsp_default_instance_;
    new (ptr) ::zproto::ServerAuthRsp();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::ServerAuthRsp::InitAsDefaultInstance();
}

void InitDefaultsServerAuthRsp() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsServerAuthRspImpl);
}

void InitDefaultsDeliveryDataToUsersReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_DeliveryDataToUsersReq_default_instance_;
    new (ptr) ::zproto::DeliveryDataToUsersReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::DeliveryDataToUsersReq::InitAsDefaultInstance();
}

void InitDefaultsDeliveryDataToUsersReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsDeliveryDataToUsersReqImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ServerAuthReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ServerAuthReq, server_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ServerAuthReq, server_name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::ServerAuthRsp, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::DeliveryDataToUsersReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::DeliveryDataToUsersReq, my_conn_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::DeliveryDataToUsersReq, uid_list_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::DeliveryDataToUsersReq, raw_data_header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::DeliveryDataToUsersReq, raw_data_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::zproto::ServerAuthReq)},
  { 7, -1, sizeof(::zproto::ServerAuthRsp)},
  { 12, -1, sizeof(::zproto::DeliveryDataToUsersReq)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ServerAuthReq_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_ServerAuthRsp_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_DeliveryDataToUsersReq_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "servers.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rservers.proto\022\006zproto\"7\n\rServerAuthReq"
      "\022\021\n\tserver_id\030\001 \001(\r\022\023\n\013server_name\030\002 \001(\t"
      "\"\017\n\rServerAuthRsp\"i\n\026DeliveryDataToUsers"
      "Req\022\022\n\nmy_conn_id\030\001 \001(\004\022\020\n\010uid_list\030\002 \003("
      "\t\022\027\n\017raw_data_header\030\004 \001(\r\022\020\n\010raw_data\030\005"
      " \001(\014B*\n\027com.zchat.engine.zprotoB\rZProtoS"
      "erversH\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 256);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "servers.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_servers_2eproto
namespace zproto {

// ===================================================================

void ServerAuthReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerAuthReq::kServerIdFieldNumber;
const int ServerAuthReq::kServerNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerAuthReq::ServerAuthReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_servers_2eproto::InitDefaultsServerAuthReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ServerAuthReq)
}
ServerAuthReq::ServerAuthReq(const ServerAuthReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  server_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.server_name().size() > 0) {
    server_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.server_name_);
  }
  server_id_ = from.server_id_;
  // @@protoc_insertion_point(copy_constructor:zproto.ServerAuthReq)
}

void ServerAuthReq::SharedCtor() {
  server_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  server_id_ = 0u;
  _cached_size_ = 0;
}

ServerAuthReq::~ServerAuthReq() {
  // @@protoc_insertion_point(destructor:zproto.ServerAuthReq)
  SharedDtor();
}

void ServerAuthReq::SharedDtor() {
  server_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ServerAuthReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServerAuthReq::descriptor() {
  ::protobuf_servers_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_servers_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerAuthReq& ServerAuthReq::default_instance() {
  ::protobuf_servers_2eproto::InitDefaultsServerAuthReq();
  return *internal_default_instance();
}

ServerAuthReq* ServerAuthReq::New(::google::protobuf::Arena* arena) const {
  ServerAuthReq* n = new ServerAuthReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ServerAuthReq::Swap(ServerAuthReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerAuthReq::InternalSwap(ServerAuthReq* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ServerAuthReq::GetMetadata() const {
  protobuf_servers_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_servers_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ServerAuthRsp::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerAuthRsp::ServerAuthRsp()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_servers_2eproto::InitDefaultsServerAuthRsp();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.ServerAuthRsp)
}
ServerAuthRsp::ServerAuthRsp(const ServerAuthRsp& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:zproto.ServerAuthRsp)
}

void ServerAuthRsp::SharedCtor() {
  _cached_size_ = 0;
}

ServerAuthRsp::~ServerAuthRsp() {
  // @@protoc_insertion_point(destructor:zproto.ServerAuthRsp)
  SharedDtor();
}

void ServerAuthRsp::SharedDtor() {
}

void ServerAuthRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServerAuthRsp::descriptor() {
  ::protobuf_servers_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_servers_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerAuthRsp& ServerAuthRsp::default_instance() {
  ::protobuf_servers_2eproto::InitDefaultsServerAuthRsp();
  return *internal_default_instance();
}

ServerAuthRsp* ServerAuthRsp::New(::google::protobuf::Arena* arena) const {
  ServerAuthRsp* n = new ServerAuthRsp;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ServerAuthRsp::Swap(ServerAuthRsp* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerAuthRsp::InternalSwap(ServerAuthRsp* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata ServerAuthRsp::GetMetadata() const {
  protobuf_servers_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_servers_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DeliveryDataToUsersReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DeliveryDataToUsersReq::kMyConnIdFieldNumber;
const int DeliveryDataToUsersReq::kUidListFieldNumber;
const int DeliveryDataToUsersReq::kRawDataHeaderFieldNumber;
const int DeliveryDataToUsersReq::kRawDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DeliveryDataToUsersReq::DeliveryDataToUsersReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_servers_2eproto::InitDefaultsDeliveryDataToUsersReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.DeliveryDataToUsersReq)
}
DeliveryDataToUsersReq::DeliveryDataToUsersReq(const DeliveryDataToUsersReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      uid_list_(from.uid_list_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  raw_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.raw_data().size() > 0) {
    raw_data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.raw_data_);
  }
  ::memcpy(&my_conn_id_, &from.my_conn_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&raw_data_header_) -
    reinterpret_cast<char*>(&my_conn_id_)) + sizeof(raw_data_header_));
  // @@protoc_insertion_point(copy_constructor:zproto.DeliveryDataToUsersReq)
}

void DeliveryDataToUsersReq::SharedCtor() {
  raw_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&my_conn_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&raw_data_header_) -
      reinterpret_cast<char*>(&my_conn_id_)) + sizeof(raw_data_header_));
  _cached_size_ = 0;
}

DeliveryDataToUsersReq::~DeliveryDataToUsersReq() {
  // @@protoc_insertion_point(destructor:zproto.DeliveryDataToUsersReq)
  SharedDtor();
}

void DeliveryDataToUsersReq::SharedDtor() {
  raw_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DeliveryDataToUsersReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DeliveryDataToUsersReq::descriptor() {
  ::protobuf_servers_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_servers_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DeliveryDataToUsersReq& DeliveryDataToUsersReq::default_instance() {
  ::protobuf_servers_2eproto::InitDefaultsDeliveryDataToUsersReq();
  return *internal_default_instance();
}

DeliveryDataToUsersReq* DeliveryDataToUsersReq::New(::google::protobuf::Arena* arena) const {
  DeliveryDataToUsersReq* n = new DeliveryDataToUsersReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DeliveryDataToUsersReq::Swap(DeliveryDataToUsersReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DeliveryDataToUsersReq::InternalSwap(DeliveryDataToUsersReq* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata DeliveryDataToUsersReq::GetMetadata() const {
  protobuf_servers_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_servers_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace zproto

// @@protoc_insertion_point(global_scope)
