// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api_method_ids.proto

#ifndef PROTOBUF_api_5fmethod_5fids_2eproto__INCLUDED
#define PROTOBUF_api_5fmethod_5fids_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace protobuf_api_5fmethod_5fids_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
inline void InitDefaults() {
}
}  // namespace protobuf_api_5fmethod_5fids_2eproto
namespace zproto {
}  // namespace zproto
namespace zproto {

enum ApiMethodIDs {
  API_UNKNOWN = 0,
  ApiMethodIDs_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ApiMethodIDs_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ApiMethodIDs_IsValid(int value);
const ApiMethodIDs ApiMethodIDs_MIN = API_UNKNOWN;
const ApiMethodIDs ApiMethodIDs_MAX = API_UNKNOWN;
const int ApiMethodIDs_ARRAYSIZE = ApiMethodIDs_MAX + 1;

const ::google::protobuf::EnumDescriptor* ApiMethodIDs_descriptor();
inline const ::std::string& ApiMethodIDs_Name(ApiMethodIDs value) {
  return ::google::protobuf::internal::NameOfEnum(
    ApiMethodIDs_descriptor(), value);
}
inline bool ApiMethodIDs_Parse(
    const ::std::string& name, ApiMethodIDs* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ApiMethodIDs>(
    ApiMethodIDs_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::zproto::ApiMethodIDs> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zproto::ApiMethodIDs>() {
  return ::zproto::ApiMethodIDs_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_api_5fmethod_5fids_2eproto__INCLUDED
