// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: device.proto

#include "device.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace zproto {
class NotifyAboutDeviceInfoReqDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NotifyAboutDeviceInfoReq>
      _instance;
} _NotifyAboutDeviceInfoReq_default_instance_;
}  // namespace zproto
namespace protobuf_device_2eproto {
void InitDefaultsNotifyAboutDeviceInfoReqImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::zproto::_NotifyAboutDeviceInfoReq_default_instance_;
    new (ptr) ::zproto::NotifyAboutDeviceInfoReq();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::zproto::NotifyAboutDeviceInfoReq::InitAsDefaultInstance();
}

void InitDefaultsNotifyAboutDeviceInfoReq() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsNotifyAboutDeviceInfoReqImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::NotifyAboutDeviceInfoReq, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::NotifyAboutDeviceInfoReq, preferred_languages_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::zproto::NotifyAboutDeviceInfoReq, time_zone_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::zproto::NotifyAboutDeviceInfoReq)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::zproto::_NotifyAboutDeviceInfoReq_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "device.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014device.proto\022\006zproto\"J\n\030NotifyAboutDev"
      "iceInfoReq\022\033\n\023preferred_languages\030\001 \003(\t\022"
      "\021\n\ttime_zone\030\002 \001(\tB)\n\027com.zchat.engine.z"
      "protoB\014ZProtoDeviceH\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 149);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "device.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_device_2eproto
namespace zproto {

// ===================================================================

void NotifyAboutDeviceInfoReq::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NotifyAboutDeviceInfoReq::kPreferredLanguagesFieldNumber;
const int NotifyAboutDeviceInfoReq::kTimeZoneFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NotifyAboutDeviceInfoReq::NotifyAboutDeviceInfoReq()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_device_2eproto::InitDefaultsNotifyAboutDeviceInfoReq();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:zproto.NotifyAboutDeviceInfoReq)
}
NotifyAboutDeviceInfoReq::NotifyAboutDeviceInfoReq(const NotifyAboutDeviceInfoReq& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      preferred_languages_(from.preferred_languages_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  time_zone_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.time_zone().size() > 0) {
    time_zone_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_zone_);
  }
  // @@protoc_insertion_point(copy_constructor:zproto.NotifyAboutDeviceInfoReq)
}

void NotifyAboutDeviceInfoReq::SharedCtor() {
  time_zone_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

NotifyAboutDeviceInfoReq::~NotifyAboutDeviceInfoReq() {
  // @@protoc_insertion_point(destructor:zproto.NotifyAboutDeviceInfoReq)
  SharedDtor();
}

void NotifyAboutDeviceInfoReq::SharedDtor() {
  time_zone_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void NotifyAboutDeviceInfoReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NotifyAboutDeviceInfoReq::descriptor() {
  ::protobuf_device_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_device_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NotifyAboutDeviceInfoReq& NotifyAboutDeviceInfoReq::default_instance() {
  ::protobuf_device_2eproto::InitDefaultsNotifyAboutDeviceInfoReq();
  return *internal_default_instance();
}

NotifyAboutDeviceInfoReq* NotifyAboutDeviceInfoReq::New(::google::protobuf::Arena* arena) const {
  NotifyAboutDeviceInfoReq* n = new NotifyAboutDeviceInfoReq;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void NotifyAboutDeviceInfoReq::Swap(NotifyAboutDeviceInfoReq* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NotifyAboutDeviceInfoReq::InternalSwap(NotifyAboutDeviceInfoReq* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata NotifyAboutDeviceInfoReq::GetMetadata() const {
  protobuf_device_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_device_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace zproto

// @@protoc_insertion_point(global_scope)
