// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: files.proto

#ifndef PROTOBUF_files_2eproto__INCLUDED
#define PROTOBUF_files_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_files_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsFileLocationImpl();
void InitDefaultsFileLocation();
void InitDefaultsAvatarImageImpl();
void InitDefaultsAvatarImage();
void InitDefaultsAvatarImpl();
void InitDefaultsAvatar();
inline void InitDefaults() {
  InitDefaultsFileLocation();
  InitDefaultsAvatarImage();
  InitDefaultsAvatar();
}
}  // namespace protobuf_files_2eproto
namespace zproto {
class Avatar;
class AvatarDefaultTypeInternal;
extern AvatarDefaultTypeInternal _Avatar_default_instance_;
class AvatarImage;
class AvatarImageDefaultTypeInternal;
extern AvatarImageDefaultTypeInternal _AvatarImage_default_instance_;
class FileLocation;
class FileLocationDefaultTypeInternal;
extern FileLocationDefaultTypeInternal _FileLocation_default_instance_;
}  // namespace zproto
namespace zproto {

// ===================================================================

class FileLocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.FileLocation) */ {
 public:
  FileLocation();
  virtual ~FileLocation();

  FileLocation(const FileLocation& from);

  inline FileLocation& operator=(const FileLocation& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  FileLocation(FileLocation&& from) noexcept
    : FileLocation() {
    *this = ::std::move(from);
  }

  inline FileLocation& operator=(FileLocation&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const FileLocation& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileLocation* internal_default_instance() {
    return reinterpret_cast<const FileLocation*>(
               &_FileLocation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(FileLocation* other);
  friend void swap(FileLocation& a, FileLocation& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline FileLocation* New() const PROTOBUF_FINAL { return New(NULL); }

  FileLocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(FileLocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 file_id = 1;
  void clear_file_id();
  static const int kFileIdFieldNumber = 1;
  ::google::protobuf::int64 file_id() const;
  void set_file_id(::google::protobuf::int64 value);

  // int64 access_hash = 2;
  void clear_access_hash();
  static const int kAccessHashFieldNumber = 2;
  ::google::protobuf::int64 access_hash() const;
  void set_access_hash(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:zproto.FileLocation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 file_id_;
  ::google::protobuf::int64 access_hash_;
  mutable int _cached_size_;
  friend struct ::protobuf_files_2eproto::TableStruct;
  friend void ::protobuf_files_2eproto::InitDefaultsFileLocationImpl();
};
// -------------------------------------------------------------------

class AvatarImage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.AvatarImage) */ {
 public:
  AvatarImage();
  virtual ~AvatarImage();

  AvatarImage(const AvatarImage& from);

  inline AvatarImage& operator=(const AvatarImage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AvatarImage(AvatarImage&& from) noexcept
    : AvatarImage() {
    *this = ::std::move(from);
  }

  inline AvatarImage& operator=(AvatarImage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AvatarImage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AvatarImage* internal_default_instance() {
    return reinterpret_cast<const AvatarImage*>(
               &_AvatarImage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(AvatarImage* other);
  friend void swap(AvatarImage& a, AvatarImage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AvatarImage* New() const PROTOBUF_FINAL { return New(NULL); }

  AvatarImage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AvatarImage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zproto.FileLocation file_location = 1;
  bool has_file_location() const;
  void clear_file_location();
  static const int kFileLocationFieldNumber = 1;
  const ::zproto::FileLocation& file_location() const;
  ::zproto::FileLocation* release_file_location();
  ::zproto::FileLocation* mutable_file_location();
  void set_allocated_file_location(::zproto::FileLocation* file_location);

  // int32 width = 2;
  void clear_width();
  static const int kWidthFieldNumber = 2;
  ::google::protobuf::int32 width() const;
  void set_width(::google::protobuf::int32 value);

  // int32 height = 3;
  void clear_height();
  static const int kHeightFieldNumber = 3;
  ::google::protobuf::int32 height() const;
  void set_height(::google::protobuf::int32 value);

  // int32 file_size = 4;
  void clear_file_size();
  static const int kFileSizeFieldNumber = 4;
  ::google::protobuf::int32 file_size() const;
  void set_file_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zproto.AvatarImage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zproto::FileLocation* file_location_;
  ::google::protobuf::int32 width_;
  ::google::protobuf::int32 height_;
  ::google::protobuf::int32 file_size_;
  mutable int _cached_size_;
  friend struct ::protobuf_files_2eproto::TableStruct;
  friend void ::protobuf_files_2eproto::InitDefaultsAvatarImageImpl();
};
// -------------------------------------------------------------------

class Avatar : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.Avatar) */ {
 public:
  Avatar();
  virtual ~Avatar();

  Avatar(const Avatar& from);

  inline Avatar& operator=(const Avatar& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Avatar(Avatar&& from) noexcept
    : Avatar() {
    *this = ::std::move(from);
  }

  inline Avatar& operator=(Avatar&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Avatar& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Avatar* internal_default_instance() {
    return reinterpret_cast<const Avatar*>(
               &_Avatar_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Avatar* other);
  friend void swap(Avatar& a, Avatar& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Avatar* New() const PROTOBUF_FINAL { return New(NULL); }

  Avatar* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Avatar* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zproto.AvatarImage small_image = 1;
  bool has_small_image() const;
  void clear_small_image();
  static const int kSmallImageFieldNumber = 1;
  const ::zproto::AvatarImage& small_image() const;
  ::zproto::AvatarImage* release_small_image();
  ::zproto::AvatarImage* mutable_small_image();
  void set_allocated_small_image(::zproto::AvatarImage* small_image);

  // .zproto.AvatarImage large_image = 2;
  bool has_large_image() const;
  void clear_large_image();
  static const int kLargeImageFieldNumber = 2;
  const ::zproto::AvatarImage& large_image() const;
  ::zproto::AvatarImage* release_large_image();
  ::zproto::AvatarImage* mutable_large_image();
  void set_allocated_large_image(::zproto::AvatarImage* large_image);

  // .zproto.AvatarImage full_image = 3;
  bool has_full_image() const;
  void clear_full_image();
  static const int kFullImageFieldNumber = 3;
  const ::zproto::AvatarImage& full_image() const;
  ::zproto::AvatarImage* release_full_image();
  ::zproto::AvatarImage* mutable_full_image();
  void set_allocated_full_image(::zproto::AvatarImage* full_image);

  // @@protoc_insertion_point(class_scope:zproto.Avatar)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zproto::AvatarImage* small_image_;
  ::zproto::AvatarImage* large_image_;
  ::zproto::AvatarImage* full_image_;
  mutable int _cached_size_;
  friend struct ::protobuf_files_2eproto::TableStruct;
  friend void ::protobuf_files_2eproto::InitDefaultsAvatarImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileLocation

// int64 file_id = 1;
inline void FileLocation::clear_file_id() {
  file_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 FileLocation::file_id() const {
  // @@protoc_insertion_point(field_get:zproto.FileLocation.file_id)
  return file_id_;
}
inline void FileLocation::set_file_id(::google::protobuf::int64 value) {
  
  file_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.FileLocation.file_id)
}

// int64 access_hash = 2;
inline void FileLocation::clear_access_hash() {
  access_hash_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 FileLocation::access_hash() const {
  // @@protoc_insertion_point(field_get:zproto.FileLocation.access_hash)
  return access_hash_;
}
inline void FileLocation::set_access_hash(::google::protobuf::int64 value) {
  
  access_hash_ = value;
  // @@protoc_insertion_point(field_set:zproto.FileLocation.access_hash)
}

// -------------------------------------------------------------------

// AvatarImage

// .zproto.FileLocation file_location = 1;
inline bool AvatarImage::has_file_location() const {
  return this != internal_default_instance() && file_location_ != NULL;
}
inline void AvatarImage::clear_file_location() {
  if (GetArenaNoVirtual() == NULL && file_location_ != NULL) {
    delete file_location_;
  }
  file_location_ = NULL;
}
inline const ::zproto::FileLocation& AvatarImage::file_location() const {
  const ::zproto::FileLocation* p = file_location_;
  // @@protoc_insertion_point(field_get:zproto.AvatarImage.file_location)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::FileLocation*>(
      &::zproto::_FileLocation_default_instance_);
}
inline ::zproto::FileLocation* AvatarImage::release_file_location() {
  // @@protoc_insertion_point(field_release:zproto.AvatarImage.file_location)
  
  ::zproto::FileLocation* temp = file_location_;
  file_location_ = NULL;
  return temp;
}
inline ::zproto::FileLocation* AvatarImage::mutable_file_location() {
  
  if (file_location_ == NULL) {
    file_location_ = new ::zproto::FileLocation;
  }
  // @@protoc_insertion_point(field_mutable:zproto.AvatarImage.file_location)
  return file_location_;
}
inline void AvatarImage::set_allocated_file_location(::zproto::FileLocation* file_location) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete file_location_;
  }
  if (file_location) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      file_location = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, file_location, submessage_arena);
    }
    
  } else {
    
  }
  file_location_ = file_location;
  // @@protoc_insertion_point(field_set_allocated:zproto.AvatarImage.file_location)
}

// int32 width = 2;
inline void AvatarImage::clear_width() {
  width_ = 0;
}
inline ::google::protobuf::int32 AvatarImage::width() const {
  // @@protoc_insertion_point(field_get:zproto.AvatarImage.width)
  return width_;
}
inline void AvatarImage::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:zproto.AvatarImage.width)
}

// int32 height = 3;
inline void AvatarImage::clear_height() {
  height_ = 0;
}
inline ::google::protobuf::int32 AvatarImage::height() const {
  // @@protoc_insertion_point(field_get:zproto.AvatarImage.height)
  return height_;
}
inline void AvatarImage::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:zproto.AvatarImage.height)
}

// int32 file_size = 4;
inline void AvatarImage::clear_file_size() {
  file_size_ = 0;
}
inline ::google::protobuf::int32 AvatarImage::file_size() const {
  // @@protoc_insertion_point(field_get:zproto.AvatarImage.file_size)
  return file_size_;
}
inline void AvatarImage::set_file_size(::google::protobuf::int32 value) {
  
  file_size_ = value;
  // @@protoc_insertion_point(field_set:zproto.AvatarImage.file_size)
}

// -------------------------------------------------------------------

// Avatar

// .zproto.AvatarImage small_image = 1;
inline bool Avatar::has_small_image() const {
  return this != internal_default_instance() && small_image_ != NULL;
}
inline void Avatar::clear_small_image() {
  if (GetArenaNoVirtual() == NULL && small_image_ != NULL) {
    delete small_image_;
  }
  small_image_ = NULL;
}
inline const ::zproto::AvatarImage& Avatar::small_image() const {
  const ::zproto::AvatarImage* p = small_image_;
  // @@protoc_insertion_point(field_get:zproto.Avatar.small_image)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::AvatarImage*>(
      &::zproto::_AvatarImage_default_instance_);
}
inline ::zproto::AvatarImage* Avatar::release_small_image() {
  // @@protoc_insertion_point(field_release:zproto.Avatar.small_image)
  
  ::zproto::AvatarImage* temp = small_image_;
  small_image_ = NULL;
  return temp;
}
inline ::zproto::AvatarImage* Avatar::mutable_small_image() {
  
  if (small_image_ == NULL) {
    small_image_ = new ::zproto::AvatarImage;
  }
  // @@protoc_insertion_point(field_mutable:zproto.Avatar.small_image)
  return small_image_;
}
inline void Avatar::set_allocated_small_image(::zproto::AvatarImage* small_image) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete small_image_;
  }
  if (small_image) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      small_image = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, small_image, submessage_arena);
    }
    
  } else {
    
  }
  small_image_ = small_image;
  // @@protoc_insertion_point(field_set_allocated:zproto.Avatar.small_image)
}

// .zproto.AvatarImage large_image = 2;
inline bool Avatar::has_large_image() const {
  return this != internal_default_instance() && large_image_ != NULL;
}
inline void Avatar::clear_large_image() {
  if (GetArenaNoVirtual() == NULL && large_image_ != NULL) {
    delete large_image_;
  }
  large_image_ = NULL;
}
inline const ::zproto::AvatarImage& Avatar::large_image() const {
  const ::zproto::AvatarImage* p = large_image_;
  // @@protoc_insertion_point(field_get:zproto.Avatar.large_image)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::AvatarImage*>(
      &::zproto::_AvatarImage_default_instance_);
}
inline ::zproto::AvatarImage* Avatar::release_large_image() {
  // @@protoc_insertion_point(field_release:zproto.Avatar.large_image)
  
  ::zproto::AvatarImage* temp = large_image_;
  large_image_ = NULL;
  return temp;
}
inline ::zproto::AvatarImage* Avatar::mutable_large_image() {
  
  if (large_image_ == NULL) {
    large_image_ = new ::zproto::AvatarImage;
  }
  // @@protoc_insertion_point(field_mutable:zproto.Avatar.large_image)
  return large_image_;
}
inline void Avatar::set_allocated_large_image(::zproto::AvatarImage* large_image) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete large_image_;
  }
  if (large_image) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      large_image = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, large_image, submessage_arena);
    }
    
  } else {
    
  }
  large_image_ = large_image;
  // @@protoc_insertion_point(field_set_allocated:zproto.Avatar.large_image)
}

// .zproto.AvatarImage full_image = 3;
inline bool Avatar::has_full_image() const {
  return this != internal_default_instance() && full_image_ != NULL;
}
inline void Avatar::clear_full_image() {
  if (GetArenaNoVirtual() == NULL && full_image_ != NULL) {
    delete full_image_;
  }
  full_image_ = NULL;
}
inline const ::zproto::AvatarImage& Avatar::full_image() const {
  const ::zproto::AvatarImage* p = full_image_;
  // @@protoc_insertion_point(field_get:zproto.Avatar.full_image)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::AvatarImage*>(
      &::zproto::_AvatarImage_default_instance_);
}
inline ::zproto::AvatarImage* Avatar::release_full_image() {
  // @@protoc_insertion_point(field_release:zproto.Avatar.full_image)
  
  ::zproto::AvatarImage* temp = full_image_;
  full_image_ = NULL;
  return temp;
}
inline ::zproto::AvatarImage* Avatar::mutable_full_image() {
  
  if (full_image_ == NULL) {
    full_image_ = new ::zproto::AvatarImage;
  }
  // @@protoc_insertion_point(field_mutable:zproto.Avatar.full_image)
  return full_image_;
}
inline void Avatar::set_allocated_full_image(::zproto::AvatarImage* full_image) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete full_image_;
  }
  if (full_image) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      full_image = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, full_image, submessage_arena);
    }
    
  } else {
    
  }
  full_image_ = full_image;
  // @@protoc_insertion_point(field_set_allocated:zproto.Avatar.full_image)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_files_2eproto__INCLUDED
