// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weak.proto

#ifndef PROTOBUF_weak_2eproto__INCLUDED
#define PROTOBUF_weak_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "peers.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_weak_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[13];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsTypingReqImpl();
void InitDefaultsTypingReq();
void InitDefaultsStopTypingReqImpl();
void InitDefaultsStopTypingReq();
void InitDefaultsSetOnlineReqImpl();
void InitDefaultsSetOnlineReq();
void InitDefaultsPauseNotificationsNotifyImpl();
void InitDefaultsPauseNotificationsNotify();
void InitDefaultsRestoreNotificationsNotifyImpl();
void InitDefaultsRestoreNotificationsNotify();
void InitDefaultsPauseNotificationsReqImpl();
void InitDefaultsPauseNotificationsReq();
void InitDefaultsRestoreNotificationsReqImpl();
void InitDefaultsRestoreNotificationsReq();
void InitDefaultsTypingNotifyImpl();
void InitDefaultsTypingNotify();
void InitDefaultsTypingStopNotifyImpl();
void InitDefaultsTypingStopNotify();
void InitDefaultsUserOnlineNotifyImpl();
void InitDefaultsUserOnlineNotify();
void InitDefaultsUserOfflineNotifyImpl();
void InitDefaultsUserOfflineNotify();
void InitDefaultsUserLastSeenNotifyImpl();
void InitDefaultsUserLastSeenNotify();
void InitDefaultsGroupOnlineNotifyImpl();
void InitDefaultsGroupOnlineNotify();
inline void InitDefaults() {
  InitDefaultsTypingReq();
  InitDefaultsStopTypingReq();
  InitDefaultsSetOnlineReq();
  InitDefaultsPauseNotificationsNotify();
  InitDefaultsRestoreNotificationsNotify();
  InitDefaultsPauseNotificationsReq();
  InitDefaultsRestoreNotificationsReq();
  InitDefaultsTypingNotify();
  InitDefaultsTypingStopNotify();
  InitDefaultsUserOnlineNotify();
  InitDefaultsUserOfflineNotify();
  InitDefaultsUserLastSeenNotify();
  InitDefaultsGroupOnlineNotify();
}
}  // namespace protobuf_weak_2eproto
namespace zproto {
class GroupOnlineNotify;
class GroupOnlineNotifyDefaultTypeInternal;
extern GroupOnlineNotifyDefaultTypeInternal _GroupOnlineNotify_default_instance_;
class PauseNotificationsNotify;
class PauseNotificationsNotifyDefaultTypeInternal;
extern PauseNotificationsNotifyDefaultTypeInternal _PauseNotificationsNotify_default_instance_;
class PauseNotificationsReq;
class PauseNotificationsReqDefaultTypeInternal;
extern PauseNotificationsReqDefaultTypeInternal _PauseNotificationsReq_default_instance_;
class RestoreNotificationsNotify;
class RestoreNotificationsNotifyDefaultTypeInternal;
extern RestoreNotificationsNotifyDefaultTypeInternal _RestoreNotificationsNotify_default_instance_;
class RestoreNotificationsReq;
class RestoreNotificationsReqDefaultTypeInternal;
extern RestoreNotificationsReqDefaultTypeInternal _RestoreNotificationsReq_default_instance_;
class SetOnlineReq;
class SetOnlineReqDefaultTypeInternal;
extern SetOnlineReqDefaultTypeInternal _SetOnlineReq_default_instance_;
class StopTypingReq;
class StopTypingReqDefaultTypeInternal;
extern StopTypingReqDefaultTypeInternal _StopTypingReq_default_instance_;
class TypingNotify;
class TypingNotifyDefaultTypeInternal;
extern TypingNotifyDefaultTypeInternal _TypingNotify_default_instance_;
class TypingReq;
class TypingReqDefaultTypeInternal;
extern TypingReqDefaultTypeInternal _TypingReq_default_instance_;
class TypingStopNotify;
class TypingStopNotifyDefaultTypeInternal;
extern TypingStopNotifyDefaultTypeInternal _TypingStopNotify_default_instance_;
class UserLastSeenNotify;
class UserLastSeenNotifyDefaultTypeInternal;
extern UserLastSeenNotifyDefaultTypeInternal _UserLastSeenNotify_default_instance_;
class UserOfflineNotify;
class UserOfflineNotifyDefaultTypeInternal;
extern UserOfflineNotifyDefaultTypeInternal _UserOfflineNotify_default_instance_;
class UserOnlineNotify;
class UserOnlineNotifyDefaultTypeInternal;
extern UserOnlineNotifyDefaultTypeInternal _UserOnlineNotify_default_instance_;
}  // namespace zproto
namespace zproto {

enum TypingType {
  kTypingType_Text = 0,
  TypingType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  TypingType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool TypingType_IsValid(int value);
const TypingType TypingType_MIN = kTypingType_Text;
const TypingType TypingType_MAX = kTypingType_Text;
const int TypingType_ARRAYSIZE = TypingType_MAX + 1;

const ::google::protobuf::EnumDescriptor* TypingType_descriptor();
inline const ::std::string& TypingType_Name(TypingType value) {
  return ::google::protobuf::internal::NameOfEnum(
    TypingType_descriptor(), value);
}
inline bool TypingType_Parse(
    const ::std::string& name, TypingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TypingType>(
    TypingType_descriptor(), name, value);
}
enum DeviceType {
  kDeviceType_GENERIC = 0,
  kDeviceType_PC = 1,
  kDeviceType_MOBILE = 2,
  kDeviceType_TABLET = 3,
  kDeviceType_WATCH = 4,
  kDeviceType_MIRROR = 5,
  kDeviceType_CAR = 6,
  kDeviceType_TABLE = 7,
  DeviceType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  DeviceType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool DeviceType_IsValid(int value);
const DeviceType DeviceType_MIN = kDeviceType_GENERIC;
const DeviceType DeviceType_MAX = kDeviceType_TABLE;
const int DeviceType_ARRAYSIZE = DeviceType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DeviceType_descriptor();
inline const ::std::string& DeviceType_Name(DeviceType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DeviceType_descriptor(), value);
}
inline bool DeviceType_Parse(
    const ::std::string& name, DeviceType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DeviceType>(
    DeviceType_descriptor(), name, value);
}
// ===================================================================

class TypingReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.TypingReq) */ {
 public:
  TypingReq();
  virtual ~TypingReq();

  TypingReq(const TypingReq& from);

  inline TypingReq& operator=(const TypingReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TypingReq(TypingReq&& from) noexcept
    : TypingReq() {
    *this = ::std::move(from);
  }

  inline TypingReq& operator=(TypingReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TypingReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TypingReq* internal_default_instance() {
    return reinterpret_cast<const TypingReq*>(
               &_TypingReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TypingReq* other);
  friend void swap(TypingReq& a, TypingReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TypingReq* New() const PROTOBUF_FINAL { return New(NULL); }

  TypingReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TypingReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zproto.OutPeer peer = 1;
  bool has_peer() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  const ::zproto::OutPeer& peer() const;
  ::zproto::OutPeer* release_peer();
  ::zproto::OutPeer* mutable_peer();
  void set_allocated_peer(::zproto::OutPeer* peer);

  // .zproto.TypingType typing_type = 3;
  void clear_typing_type();
  static const int kTypingTypeFieldNumber = 3;
  ::zproto::TypingType typing_type() const;
  void set_typing_type(::zproto::TypingType value);

  // @@protoc_insertion_point(class_scope:zproto.TypingReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zproto::OutPeer* peer_;
  int typing_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsTypingReqImpl();
};
// -------------------------------------------------------------------

class StopTypingReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.StopTypingReq) */ {
 public:
  StopTypingReq();
  virtual ~StopTypingReq();

  StopTypingReq(const StopTypingReq& from);

  inline StopTypingReq& operator=(const StopTypingReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StopTypingReq(StopTypingReq&& from) noexcept
    : StopTypingReq() {
    *this = ::std::move(from);
  }

  inline StopTypingReq& operator=(StopTypingReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StopTypingReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StopTypingReq* internal_default_instance() {
    return reinterpret_cast<const StopTypingReq*>(
               &_StopTypingReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(StopTypingReq* other);
  friend void swap(StopTypingReq& a, StopTypingReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StopTypingReq* New() const PROTOBUF_FINAL { return New(NULL); }

  StopTypingReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StopTypingReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zproto.OutPeer peer = 1;
  bool has_peer() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  const ::zproto::OutPeer& peer() const;
  ::zproto::OutPeer* release_peer();
  ::zproto::OutPeer* mutable_peer();
  void set_allocated_peer(::zproto::OutPeer* peer);

  // .zproto.TypingType typing_type = 2;
  void clear_typing_type();
  static const int kTypingTypeFieldNumber = 2;
  ::zproto::TypingType typing_type() const;
  void set_typing_type(::zproto::TypingType value);

  // @@protoc_insertion_point(class_scope:zproto.StopTypingReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zproto::OutPeer* peer_;
  int typing_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsStopTypingReqImpl();
};
// -------------------------------------------------------------------

class SetOnlineReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.SetOnlineReq) */ {
 public:
  SetOnlineReq();
  virtual ~SetOnlineReq();

  SetOnlineReq(const SetOnlineReq& from);

  inline SetOnlineReq& operator=(const SetOnlineReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetOnlineReq(SetOnlineReq&& from) noexcept
    : SetOnlineReq() {
    *this = ::std::move(from);
  }

  inline SetOnlineReq& operator=(SetOnlineReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SetOnlineReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetOnlineReq* internal_default_instance() {
    return reinterpret_cast<const SetOnlineReq*>(
               &_SetOnlineReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SetOnlineReq* other);
  friend void swap(SetOnlineReq& a, SetOnlineReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetOnlineReq* New() const PROTOBUF_FINAL { return New(NULL); }

  SetOnlineReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetOnlineReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_category = 4;
  void clear_device_category();
  static const int kDeviceCategoryFieldNumber = 4;
  const ::std::string& device_category() const;
  void set_device_category(const ::std::string& value);
  #if LANG_CXX11
  void set_device_category(::std::string&& value);
  #endif
  void set_device_category(const char* value);
  void set_device_category(const char* value, size_t size);
  ::std::string* mutable_device_category();
  ::std::string* release_device_category();
  void set_allocated_device_category(::std::string* device_category);

  // int64 timeout = 2;
  void clear_timeout();
  static const int kTimeoutFieldNumber = 2;
  ::google::protobuf::int64 timeout() const;
  void set_timeout(::google::protobuf::int64 value);

  // bool is_online = 1;
  void clear_is_online();
  static const int kIsOnlineFieldNumber = 1;
  bool is_online() const;
  void set_is_online(bool value);

  // .zproto.DeviceType device_type = 3;
  void clear_device_type();
  static const int kDeviceTypeFieldNumber = 3;
  ::zproto::DeviceType device_type() const;
  void set_device_type(::zproto::DeviceType value);

  // @@protoc_insertion_point(class_scope:zproto.SetOnlineReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_category_;
  ::google::protobuf::int64 timeout_;
  bool is_online_;
  int device_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsSetOnlineReqImpl();
};
// -------------------------------------------------------------------

class PauseNotificationsNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.PauseNotificationsNotify) */ {
 public:
  PauseNotificationsNotify();
  virtual ~PauseNotificationsNotify();

  PauseNotificationsNotify(const PauseNotificationsNotify& from);

  inline PauseNotificationsNotify& operator=(const PauseNotificationsNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PauseNotificationsNotify(PauseNotificationsNotify&& from) noexcept
    : PauseNotificationsNotify() {
    *this = ::std::move(from);
  }

  inline PauseNotificationsNotify& operator=(PauseNotificationsNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PauseNotificationsNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PauseNotificationsNotify* internal_default_instance() {
    return reinterpret_cast<const PauseNotificationsNotify*>(
               &_PauseNotificationsNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PauseNotificationsNotify* other);
  friend void swap(PauseNotificationsNotify& a, PauseNotificationsNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PauseNotificationsNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  PauseNotificationsNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PauseNotificationsNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 timeout = 1;
  void clear_timeout();
  static const int kTimeoutFieldNumber = 1;
  ::google::protobuf::int32 timeout() const;
  void set_timeout(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zproto.PauseNotificationsNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 timeout_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsPauseNotificationsNotifyImpl();
};
// -------------------------------------------------------------------

class RestoreNotificationsNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.RestoreNotificationsNotify) */ {
 public:
  RestoreNotificationsNotify();
  virtual ~RestoreNotificationsNotify();

  RestoreNotificationsNotify(const RestoreNotificationsNotify& from);

  inline RestoreNotificationsNotify& operator=(const RestoreNotificationsNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RestoreNotificationsNotify(RestoreNotificationsNotify&& from) noexcept
    : RestoreNotificationsNotify() {
    *this = ::std::move(from);
  }

  inline RestoreNotificationsNotify& operator=(RestoreNotificationsNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RestoreNotificationsNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RestoreNotificationsNotify* internal_default_instance() {
    return reinterpret_cast<const RestoreNotificationsNotify*>(
               &_RestoreNotificationsNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(RestoreNotificationsNotify* other);
  friend void swap(RestoreNotificationsNotify& a, RestoreNotificationsNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RestoreNotificationsNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  RestoreNotificationsNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RestoreNotificationsNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:zproto.RestoreNotificationsNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsRestoreNotificationsNotifyImpl();
};
// -------------------------------------------------------------------

class PauseNotificationsReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.PauseNotificationsReq) */ {
 public:
  PauseNotificationsReq();
  virtual ~PauseNotificationsReq();

  PauseNotificationsReq(const PauseNotificationsReq& from);

  inline PauseNotificationsReq& operator=(const PauseNotificationsReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PauseNotificationsReq(PauseNotificationsReq&& from) noexcept
    : PauseNotificationsReq() {
    *this = ::std::move(from);
  }

  inline PauseNotificationsReq& operator=(PauseNotificationsReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PauseNotificationsReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PauseNotificationsReq* internal_default_instance() {
    return reinterpret_cast<const PauseNotificationsReq*>(
               &_PauseNotificationsReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(PauseNotificationsReq* other);
  friend void swap(PauseNotificationsReq& a, PauseNotificationsReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PauseNotificationsReq* New() const PROTOBUF_FINAL { return New(NULL); }

  PauseNotificationsReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PauseNotificationsReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 timeout = 1;
  void clear_timeout();
  static const int kTimeoutFieldNumber = 1;
  ::google::protobuf::int32 timeout() const;
  void set_timeout(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zproto.PauseNotificationsReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 timeout_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsPauseNotificationsReqImpl();
};
// -------------------------------------------------------------------

class RestoreNotificationsReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.RestoreNotificationsReq) */ {
 public:
  RestoreNotificationsReq();
  virtual ~RestoreNotificationsReq();

  RestoreNotificationsReq(const RestoreNotificationsReq& from);

  inline RestoreNotificationsReq& operator=(const RestoreNotificationsReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RestoreNotificationsReq(RestoreNotificationsReq&& from) noexcept
    : RestoreNotificationsReq() {
    *this = ::std::move(from);
  }

  inline RestoreNotificationsReq& operator=(RestoreNotificationsReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RestoreNotificationsReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RestoreNotificationsReq* internal_default_instance() {
    return reinterpret_cast<const RestoreNotificationsReq*>(
               &_RestoreNotificationsReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(RestoreNotificationsReq* other);
  friend void swap(RestoreNotificationsReq& a, RestoreNotificationsReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RestoreNotificationsReq* New() const PROTOBUF_FINAL { return New(NULL); }

  RestoreNotificationsReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RestoreNotificationsReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:zproto.RestoreNotificationsReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsRestoreNotificationsReqImpl();
};
// -------------------------------------------------------------------

class TypingNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.TypingNotify) */ {
 public:
  TypingNotify();
  virtual ~TypingNotify();

  TypingNotify(const TypingNotify& from);

  inline TypingNotify& operator=(const TypingNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TypingNotify(TypingNotify&& from) noexcept
    : TypingNotify() {
    *this = ::std::move(from);
  }

  inline TypingNotify& operator=(TypingNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TypingNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TypingNotify* internal_default_instance() {
    return reinterpret_cast<const TypingNotify*>(
               &_TypingNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(TypingNotify* other);
  friend void swap(TypingNotify& a, TypingNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TypingNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  TypingNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TypingNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zproto.Peer peer = 1;
  bool has_peer() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  const ::zproto::Peer& peer() const;
  ::zproto::Peer* release_peer();
  ::zproto::Peer* mutable_peer();
  void set_allocated_peer(::zproto::Peer* peer);

  // int32 uid = 2;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // .zproto.TypingType typing_type = 3;
  void clear_typing_type();
  static const int kTypingTypeFieldNumber = 3;
  ::zproto::TypingType typing_type() const;
  void set_typing_type(::zproto::TypingType value);

  // @@protoc_insertion_point(class_scope:zproto.TypingNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zproto::Peer* peer_;
  ::google::protobuf::int32 uid_;
  int typing_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsTypingNotifyImpl();
};
// -------------------------------------------------------------------

class TypingStopNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.TypingStopNotify) */ {
 public:
  TypingStopNotify();
  virtual ~TypingStopNotify();

  TypingStopNotify(const TypingStopNotify& from);

  inline TypingStopNotify& operator=(const TypingStopNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TypingStopNotify(TypingStopNotify&& from) noexcept
    : TypingStopNotify() {
    *this = ::std::move(from);
  }

  inline TypingStopNotify& operator=(TypingStopNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TypingStopNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TypingStopNotify* internal_default_instance() {
    return reinterpret_cast<const TypingStopNotify*>(
               &_TypingStopNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(TypingStopNotify* other);
  friend void swap(TypingStopNotify& a, TypingStopNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TypingStopNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  TypingStopNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TypingStopNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .zproto.Peer peer = 1;
  bool has_peer() const;
  void clear_peer();
  static const int kPeerFieldNumber = 1;
  const ::zproto::Peer& peer() const;
  ::zproto::Peer* release_peer();
  ::zproto::Peer* mutable_peer();
  void set_allocated_peer(::zproto::Peer* peer);

  // int32 uid = 2;
  void clear_uid();
  static const int kUidFieldNumber = 2;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // .zproto.TypingType typing_type = 3;
  void clear_typing_type();
  static const int kTypingTypeFieldNumber = 3;
  ::zproto::TypingType typing_type() const;
  void set_typing_type(::zproto::TypingType value);

  // @@protoc_insertion_point(class_scope:zproto.TypingStopNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::zproto::Peer* peer_;
  ::google::protobuf::int32 uid_;
  int typing_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsTypingStopNotifyImpl();
};
// -------------------------------------------------------------------

class UserOnlineNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.UserOnlineNotify) */ {
 public:
  UserOnlineNotify();
  virtual ~UserOnlineNotify();

  UserOnlineNotify(const UserOnlineNotify& from);

  inline UserOnlineNotify& operator=(const UserOnlineNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserOnlineNotify(UserOnlineNotify&& from) noexcept
    : UserOnlineNotify() {
    *this = ::std::move(from);
  }

  inline UserOnlineNotify& operator=(UserOnlineNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserOnlineNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserOnlineNotify* internal_default_instance() {
    return reinterpret_cast<const UserOnlineNotify*>(
               &_UserOnlineNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(UserOnlineNotify* other);
  friend void swap(UserOnlineNotify& a, UserOnlineNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserOnlineNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  UserOnlineNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserOnlineNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_category = 3;
  void clear_device_category();
  static const int kDeviceCategoryFieldNumber = 3;
  const ::std::string& device_category() const;
  void set_device_category(const ::std::string& value);
  #if LANG_CXX11
  void set_device_category(::std::string&& value);
  #endif
  void set_device_category(const char* value);
  void set_device_category(const char* value, size_t size);
  ::std::string* mutable_device_category();
  ::std::string* release_device_category();
  void set_allocated_device_category(::std::string* device_category);

  // int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // .zproto.DeviceType device_type = 2;
  void clear_device_type();
  static const int kDeviceTypeFieldNumber = 2;
  ::zproto::DeviceType device_type() const;
  void set_device_type(::zproto::DeviceType value);

  // @@protoc_insertion_point(class_scope:zproto.UserOnlineNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_category_;
  ::google::protobuf::int32 uid_;
  int device_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsUserOnlineNotifyImpl();
};
// -------------------------------------------------------------------

class UserOfflineNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.UserOfflineNotify) */ {
 public:
  UserOfflineNotify();
  virtual ~UserOfflineNotify();

  UserOfflineNotify(const UserOfflineNotify& from);

  inline UserOfflineNotify& operator=(const UserOfflineNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserOfflineNotify(UserOfflineNotify&& from) noexcept
    : UserOfflineNotify() {
    *this = ::std::move(from);
  }

  inline UserOfflineNotify& operator=(UserOfflineNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserOfflineNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserOfflineNotify* internal_default_instance() {
    return reinterpret_cast<const UserOfflineNotify*>(
               &_UserOfflineNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(UserOfflineNotify* other);
  friend void swap(UserOfflineNotify& a, UserOfflineNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserOfflineNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  UserOfflineNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserOfflineNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_category = 3;
  void clear_device_category();
  static const int kDeviceCategoryFieldNumber = 3;
  const ::std::string& device_category() const;
  void set_device_category(const ::std::string& value);
  #if LANG_CXX11
  void set_device_category(::std::string&& value);
  #endif
  void set_device_category(const char* value);
  void set_device_category(const char* value, size_t size);
  ::std::string* mutable_device_category();
  ::std::string* release_device_category();
  void set_allocated_device_category(::std::string* device_category);

  // int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // .zproto.DeviceType device_type = 2;
  void clear_device_type();
  static const int kDeviceTypeFieldNumber = 2;
  ::zproto::DeviceType device_type() const;
  void set_device_type(::zproto::DeviceType value);

  // @@protoc_insertion_point(class_scope:zproto.UserOfflineNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_category_;
  ::google::protobuf::int32 uid_;
  int device_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsUserOfflineNotifyImpl();
};
// -------------------------------------------------------------------

class UserLastSeenNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.UserLastSeenNotify) */ {
 public:
  UserLastSeenNotify();
  virtual ~UserLastSeenNotify();

  UserLastSeenNotify(const UserLastSeenNotify& from);

  inline UserLastSeenNotify& operator=(const UserLastSeenNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserLastSeenNotify(UserLastSeenNotify&& from) noexcept
    : UserLastSeenNotify() {
    *this = ::std::move(from);
  }

  inline UserLastSeenNotify& operator=(UserLastSeenNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UserLastSeenNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserLastSeenNotify* internal_default_instance() {
    return reinterpret_cast<const UserLastSeenNotify*>(
               &_UserLastSeenNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(UserLastSeenNotify* other);
  friend void swap(UserLastSeenNotify& a, UserLastSeenNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserLastSeenNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  UserLastSeenNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UserLastSeenNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string device_category = 4;
  void clear_device_category();
  static const int kDeviceCategoryFieldNumber = 4;
  const ::std::string& device_category() const;
  void set_device_category(const ::std::string& value);
  #if LANG_CXX11
  void set_device_category(::std::string&& value);
  #endif
  void set_device_category(const char* value);
  void set_device_category(const char* value, size_t size);
  ::std::string* mutable_device_category();
  ::std::string* release_device_category();
  void set_allocated_device_category(::std::string* device_category);

  // int64 date = 2;
  void clear_date();
  static const int kDateFieldNumber = 2;
  ::google::protobuf::int64 date() const;
  void set_date(::google::protobuf::int64 value);

  // int32 uid = 1;
  void clear_uid();
  static const int kUidFieldNumber = 1;
  ::google::protobuf::int32 uid() const;
  void set_uid(::google::protobuf::int32 value);

  // .zproto.DeviceType device_type = 3;
  void clear_device_type();
  static const int kDeviceTypeFieldNumber = 3;
  ::zproto::DeviceType device_type() const;
  void set_device_type(::zproto::DeviceType value);

  // @@protoc_insertion_point(class_scope:zproto.UserLastSeenNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr device_category_;
  ::google::protobuf::int64 date_;
  ::google::protobuf::int32 uid_;
  int device_type_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsUserLastSeenNotifyImpl();
};
// -------------------------------------------------------------------

class GroupOnlineNotify : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:zproto.GroupOnlineNotify) */ {
 public:
  GroupOnlineNotify();
  virtual ~GroupOnlineNotify();

  GroupOnlineNotify(const GroupOnlineNotify& from);

  inline GroupOnlineNotify& operator=(const GroupOnlineNotify& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GroupOnlineNotify(GroupOnlineNotify&& from) noexcept
    : GroupOnlineNotify() {
    *this = ::std::move(from);
  }

  inline GroupOnlineNotify& operator=(GroupOnlineNotify&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GroupOnlineNotify& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GroupOnlineNotify* internal_default_instance() {
    return reinterpret_cast<const GroupOnlineNotify*>(
               &_GroupOnlineNotify_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    12;

  void Swap(GroupOnlineNotify* other);
  friend void swap(GroupOnlineNotify& a, GroupOnlineNotify& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GroupOnlineNotify* New() const PROTOBUF_FINAL { return New(NULL); }

  GroupOnlineNotify* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GroupOnlineNotify* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 group_id = 1;
  void clear_group_id();
  static const int kGroupIdFieldNumber = 1;
  ::google::protobuf::int32 group_id() const;
  void set_group_id(::google::protobuf::int32 value);

  // int32 count = 2;
  void clear_count();
  static const int kCountFieldNumber = 2;
  ::google::protobuf::int32 count() const;
  void set_count(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:zproto.GroupOnlineNotify)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 group_id_;
  ::google::protobuf::int32 count_;
  mutable int _cached_size_;
  friend struct ::protobuf_weak_2eproto::TableStruct;
  friend void ::protobuf_weak_2eproto::InitDefaultsGroupOnlineNotifyImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TypingReq

// .zproto.OutPeer peer = 1;
inline bool TypingReq::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
inline const ::zproto::OutPeer& TypingReq::peer() const {
  const ::zproto::OutPeer* p = peer_;
  // @@protoc_insertion_point(field_get:zproto.TypingReq.peer)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::OutPeer*>(
      &::zproto::_OutPeer_default_instance_);
}
inline ::zproto::OutPeer* TypingReq::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.TypingReq.peer)
  
  ::zproto::OutPeer* temp = peer_;
  peer_ = NULL;
  return temp;
}
inline ::zproto::OutPeer* TypingReq::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::OutPeer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.TypingReq.peer)
  return peer_;
}
inline void TypingReq::set_allocated_peer(::zproto::OutPeer* peer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(peer_);
  }
  if (peer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      peer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, peer, submessage_arena);
    }
    
  } else {
    
  }
  peer_ = peer;
  // @@protoc_insertion_point(field_set_allocated:zproto.TypingReq.peer)
}

// .zproto.TypingType typing_type = 3;
inline void TypingReq::clear_typing_type() {
  typing_type_ = 0;
}
inline ::zproto::TypingType TypingReq::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.TypingReq.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
inline void TypingReq::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingReq.typing_type)
}

// -------------------------------------------------------------------

// StopTypingReq

// .zproto.OutPeer peer = 1;
inline bool StopTypingReq::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
inline const ::zproto::OutPeer& StopTypingReq::peer() const {
  const ::zproto::OutPeer* p = peer_;
  // @@protoc_insertion_point(field_get:zproto.StopTypingReq.peer)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::OutPeer*>(
      &::zproto::_OutPeer_default_instance_);
}
inline ::zproto::OutPeer* StopTypingReq::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.StopTypingReq.peer)
  
  ::zproto::OutPeer* temp = peer_;
  peer_ = NULL;
  return temp;
}
inline ::zproto::OutPeer* StopTypingReq::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::OutPeer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.StopTypingReq.peer)
  return peer_;
}
inline void StopTypingReq::set_allocated_peer(::zproto::OutPeer* peer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(peer_);
  }
  if (peer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      peer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, peer, submessage_arena);
    }
    
  } else {
    
  }
  peer_ = peer;
  // @@protoc_insertion_point(field_set_allocated:zproto.StopTypingReq.peer)
}

// .zproto.TypingType typing_type = 2;
inline void StopTypingReq::clear_typing_type() {
  typing_type_ = 0;
}
inline ::zproto::TypingType StopTypingReq::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.StopTypingReq.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
inline void StopTypingReq::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.StopTypingReq.typing_type)
}

// -------------------------------------------------------------------

// SetOnlineReq

// bool is_online = 1;
inline void SetOnlineReq::clear_is_online() {
  is_online_ = false;
}
inline bool SetOnlineReq::is_online() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.is_online)
  return is_online_;
}
inline void SetOnlineReq::set_is_online(bool value) {
  
  is_online_ = value;
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.is_online)
}

// int64 timeout = 2;
inline void SetOnlineReq::clear_timeout() {
  timeout_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 SetOnlineReq::timeout() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.timeout)
  return timeout_;
}
inline void SetOnlineReq::set_timeout(::google::protobuf::int64 value) {
  
  timeout_ = value;
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.timeout)
}

// .zproto.DeviceType device_type = 3;
inline void SetOnlineReq::clear_device_type() {
  device_type_ = 0;
}
inline ::zproto::DeviceType SetOnlineReq::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
inline void SetOnlineReq::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.device_type)
}

// string device_category = 4;
inline void SetOnlineReq::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SetOnlineReq::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.SetOnlineReq.device_category)
  return device_category_.GetNoArena();
}
inline void SetOnlineReq::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.SetOnlineReq.device_category)
}
#if LANG_CXX11
inline void SetOnlineReq::set_device_category(::std::string&& value) {
  
  device_category_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.SetOnlineReq.device_category)
}
#endif
inline void SetOnlineReq::set_device_category(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.SetOnlineReq.device_category)
}
inline void SetOnlineReq::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.SetOnlineReq.device_category)
}
inline ::std::string* SetOnlineReq::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.SetOnlineReq.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SetOnlineReq::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.SetOnlineReq.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SetOnlineReq::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.SetOnlineReq.device_category)
}

// -------------------------------------------------------------------

// PauseNotificationsNotify

// int32 timeout = 1;
inline void PauseNotificationsNotify::clear_timeout() {
  timeout_ = 0;
}
inline ::google::protobuf::int32 PauseNotificationsNotify::timeout() const {
  // @@protoc_insertion_point(field_get:zproto.PauseNotificationsNotify.timeout)
  return timeout_;
}
inline void PauseNotificationsNotify::set_timeout(::google::protobuf::int32 value) {
  
  timeout_ = value;
  // @@protoc_insertion_point(field_set:zproto.PauseNotificationsNotify.timeout)
}

// -------------------------------------------------------------------

// RestoreNotificationsNotify

// -------------------------------------------------------------------

// PauseNotificationsReq

// int32 timeout = 1;
inline void PauseNotificationsReq::clear_timeout() {
  timeout_ = 0;
}
inline ::google::protobuf::int32 PauseNotificationsReq::timeout() const {
  // @@protoc_insertion_point(field_get:zproto.PauseNotificationsReq.timeout)
  return timeout_;
}
inline void PauseNotificationsReq::set_timeout(::google::protobuf::int32 value) {
  
  timeout_ = value;
  // @@protoc_insertion_point(field_set:zproto.PauseNotificationsReq.timeout)
}

// -------------------------------------------------------------------

// RestoreNotificationsReq

// -------------------------------------------------------------------

// TypingNotify

// .zproto.Peer peer = 1;
inline bool TypingNotify::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
inline const ::zproto::Peer& TypingNotify::peer() const {
  const ::zproto::Peer* p = peer_;
  // @@protoc_insertion_point(field_get:zproto.TypingNotify.peer)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::Peer*>(
      &::zproto::_Peer_default_instance_);
}
inline ::zproto::Peer* TypingNotify::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.TypingNotify.peer)
  
  ::zproto::Peer* temp = peer_;
  peer_ = NULL;
  return temp;
}
inline ::zproto::Peer* TypingNotify::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::Peer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.TypingNotify.peer)
  return peer_;
}
inline void TypingNotify::set_allocated_peer(::zproto::Peer* peer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(peer_);
  }
  if (peer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      peer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, peer, submessage_arena);
    }
    
  } else {
    
  }
  peer_ = peer;
  // @@protoc_insertion_point(field_set_allocated:zproto.TypingNotify.peer)
}

// int32 uid = 2;
inline void TypingNotify::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 TypingNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.TypingNotify.uid)
  return uid_;
}
inline void TypingNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingNotify.uid)
}

// .zproto.TypingType typing_type = 3;
inline void TypingNotify::clear_typing_type() {
  typing_type_ = 0;
}
inline ::zproto::TypingType TypingNotify::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.TypingNotify.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
inline void TypingNotify::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingNotify.typing_type)
}

// -------------------------------------------------------------------

// TypingStopNotify

// .zproto.Peer peer = 1;
inline bool TypingStopNotify::has_peer() const {
  return this != internal_default_instance() && peer_ != NULL;
}
inline const ::zproto::Peer& TypingStopNotify::peer() const {
  const ::zproto::Peer* p = peer_;
  // @@protoc_insertion_point(field_get:zproto.TypingStopNotify.peer)
  return p != NULL ? *p : *reinterpret_cast<const ::zproto::Peer*>(
      &::zproto::_Peer_default_instance_);
}
inline ::zproto::Peer* TypingStopNotify::release_peer() {
  // @@protoc_insertion_point(field_release:zproto.TypingStopNotify.peer)
  
  ::zproto::Peer* temp = peer_;
  peer_ = NULL;
  return temp;
}
inline ::zproto::Peer* TypingStopNotify::mutable_peer() {
  
  if (peer_ == NULL) {
    peer_ = new ::zproto::Peer;
  }
  // @@protoc_insertion_point(field_mutable:zproto.TypingStopNotify.peer)
  return peer_;
}
inline void TypingStopNotify::set_allocated_peer(::zproto::Peer* peer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(peer_);
  }
  if (peer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      peer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, peer, submessage_arena);
    }
    
  } else {
    
  }
  peer_ = peer;
  // @@protoc_insertion_point(field_set_allocated:zproto.TypingStopNotify.peer)
}

// int32 uid = 2;
inline void TypingStopNotify::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 TypingStopNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.TypingStopNotify.uid)
  return uid_;
}
inline void TypingStopNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingStopNotify.uid)
}

// .zproto.TypingType typing_type = 3;
inline void TypingStopNotify::clear_typing_type() {
  typing_type_ = 0;
}
inline ::zproto::TypingType TypingStopNotify::typing_type() const {
  // @@protoc_insertion_point(field_get:zproto.TypingStopNotify.typing_type)
  return static_cast< ::zproto::TypingType >(typing_type_);
}
inline void TypingStopNotify::set_typing_type(::zproto::TypingType value) {
  
  typing_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.TypingStopNotify.typing_type)
}

// -------------------------------------------------------------------

// UserOnlineNotify

// int32 uid = 1;
inline void UserOnlineNotify::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 UserOnlineNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.UserOnlineNotify.uid)
  return uid_;
}
inline void UserOnlineNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOnlineNotify.uid)
}

// .zproto.DeviceType device_type = 2;
inline void UserOnlineNotify::clear_device_type() {
  device_type_ = 0;
}
inline ::zproto::DeviceType UserOnlineNotify::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.UserOnlineNotify.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
inline void UserOnlineNotify::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOnlineNotify.device_type)
}

// string device_category = 3;
inline void UserOnlineNotify::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserOnlineNotify::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.UserOnlineNotify.device_category)
  return device_category_.GetNoArena();
}
inline void UserOnlineNotify::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserOnlineNotify.device_category)
}
#if LANG_CXX11
inline void UserOnlineNotify::set_device_category(::std::string&& value) {
  
  device_category_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserOnlineNotify.device_category)
}
#endif
inline void UserOnlineNotify::set_device_category(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserOnlineNotify.device_category)
}
inline void UserOnlineNotify::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserOnlineNotify.device_category)
}
inline ::std::string* UserOnlineNotify::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserOnlineNotify.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserOnlineNotify::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.UserOnlineNotify.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserOnlineNotify::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserOnlineNotify.device_category)
}

// -------------------------------------------------------------------

// UserOfflineNotify

// int32 uid = 1;
inline void UserOfflineNotify::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 UserOfflineNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.UserOfflineNotify.uid)
  return uid_;
}
inline void UserOfflineNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOfflineNotify.uid)
}

// .zproto.DeviceType device_type = 2;
inline void UserOfflineNotify::clear_device_type() {
  device_type_ = 0;
}
inline ::zproto::DeviceType UserOfflineNotify::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.UserOfflineNotify.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
inline void UserOfflineNotify::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserOfflineNotify.device_type)
}

// string device_category = 3;
inline void UserOfflineNotify::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserOfflineNotify::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.UserOfflineNotify.device_category)
  return device_category_.GetNoArena();
}
inline void UserOfflineNotify::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserOfflineNotify.device_category)
}
#if LANG_CXX11
inline void UserOfflineNotify::set_device_category(::std::string&& value) {
  
  device_category_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserOfflineNotify.device_category)
}
#endif
inline void UserOfflineNotify::set_device_category(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserOfflineNotify.device_category)
}
inline void UserOfflineNotify::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserOfflineNotify.device_category)
}
inline ::std::string* UserOfflineNotify::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserOfflineNotify.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserOfflineNotify::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.UserOfflineNotify.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserOfflineNotify::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserOfflineNotify.device_category)
}

// -------------------------------------------------------------------

// UserLastSeenNotify

// int32 uid = 1;
inline void UserLastSeenNotify::clear_uid() {
  uid_ = 0;
}
inline ::google::protobuf::int32 UserLastSeenNotify::uid() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.uid)
  return uid_;
}
inline void UserLastSeenNotify::set_uid(::google::protobuf::int32 value) {
  
  uid_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.uid)
}

// int64 date = 2;
inline void UserLastSeenNotify::clear_date() {
  date_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 UserLastSeenNotify::date() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.date)
  return date_;
}
inline void UserLastSeenNotify::set_date(::google::protobuf::int64 value) {
  
  date_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.date)
}

// .zproto.DeviceType device_type = 3;
inline void UserLastSeenNotify::clear_device_type() {
  device_type_ = 0;
}
inline ::zproto::DeviceType UserLastSeenNotify::device_type() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.device_type)
  return static_cast< ::zproto::DeviceType >(device_type_);
}
inline void UserLastSeenNotify::set_device_type(::zproto::DeviceType value) {
  
  device_type_ = value;
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.device_type)
}

// string device_category = 4;
inline void UserLastSeenNotify::clear_device_category() {
  device_category_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& UserLastSeenNotify::device_category() const {
  // @@protoc_insertion_point(field_get:zproto.UserLastSeenNotify.device_category)
  return device_category_.GetNoArena();
}
inline void UserLastSeenNotify::set_device_category(const ::std::string& value) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:zproto.UserLastSeenNotify.device_category)
}
#if LANG_CXX11
inline void UserLastSeenNotify::set_device_category(::std::string&& value) {
  
  device_category_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:zproto.UserLastSeenNotify.device_category)
}
#endif
inline void UserLastSeenNotify::set_device_category(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:zproto.UserLastSeenNotify.device_category)
}
inline void UserLastSeenNotify::set_device_category(const char* value, size_t size) {
  
  device_category_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:zproto.UserLastSeenNotify.device_category)
}
inline ::std::string* UserLastSeenNotify::mutable_device_category() {
  
  // @@protoc_insertion_point(field_mutable:zproto.UserLastSeenNotify.device_category)
  return device_category_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserLastSeenNotify::release_device_category() {
  // @@protoc_insertion_point(field_release:zproto.UserLastSeenNotify.device_category)
  
  return device_category_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserLastSeenNotify::set_allocated_device_category(::std::string* device_category) {
  if (device_category != NULL) {
    
  } else {
    
  }
  device_category_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_category);
  // @@protoc_insertion_point(field_set_allocated:zproto.UserLastSeenNotify.device_category)
}

// -------------------------------------------------------------------

// GroupOnlineNotify

// int32 group_id = 1;
inline void GroupOnlineNotify::clear_group_id() {
  group_id_ = 0;
}
inline ::google::protobuf::int32 GroupOnlineNotify::group_id() const {
  // @@protoc_insertion_point(field_get:zproto.GroupOnlineNotify.group_id)
  return group_id_;
}
inline void GroupOnlineNotify::set_group_id(::google::protobuf::int32 value) {
  
  group_id_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupOnlineNotify.group_id)
}

// int32 count = 2;
inline void GroupOnlineNotify::clear_count() {
  count_ = 0;
}
inline ::google::protobuf::int32 GroupOnlineNotify::count() const {
  // @@protoc_insertion_point(field_get:zproto.GroupOnlineNotify.count)
  return count_;
}
inline void GroupOnlineNotify::set_count(::google::protobuf::int32 value) {
  
  count_ = value;
  // @@protoc_insertion_point(field_set:zproto.GroupOnlineNotify.count)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace zproto

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::zproto::TypingType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zproto::TypingType>() {
  return ::zproto::TypingType_descriptor();
}
template <> struct is_proto_enum< ::zproto::DeviceType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::zproto::DeviceType>() {
  return ::zproto::DeviceType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_weak_2eproto__INCLUDED
