// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auths.proto

/*
Package zproto is a generated protocol buffer package.

It is generated from these files:
	auths.proto
	bases.proto
	biz_servers.proto
	files.proto
	groups.proto
	messages.proto
	peers.proto
	presences.proto
	servers.proto

It has these top-level messages:
	UserTokenAuthReq
	UserTokenAuthRsp
	EnumHelper
	UserID
	OnlineSessionStatusEntry
	UserToeken
	UserInfo
	OnlineUser
	MessageContainer
	Dialog
	GroupMember
	Group
	CreateGroupReq
	CreateGroupRsp
	LoadMembersReq
	LoadMembersRsp
	LoadFullGroupsReq
	LoadFullGroupsRsp
	InviteUserReq
	LeaveGroupReq
	LeaveAndDeleteReq
	KickUserReq
	JoinGroupByPeerReq
	VoidRsp
	SendMessageReq
	SeqDateRsp
	ForwardMessageReq
	MessageNotify
	MessageDataNotify
	MessageSyncReq
	MessageSyncRsp
	MessageReadReq
	LoadHistoryMessageReq
	LoadHistoryMessageRsp
	LoadDialogsReq
	LoadDialogsRsp
	Peer
	OutPeer
	UserOutPeer
	GroupOutPeer
	ClientOnlineReq
	ClientOnlineRsp
	ClientOfflineReq
	ClientOfflineRsp
	QueryOnlineUserReq
	QueryOnlineUserRsp
	ServerAuthReq
	ServerAuthRsp
*/
package zproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserTokenAuthReq struct {
	AppKey    string `protobuf:"bytes,1,opt,name=app_key,json=appKey" json:"app_key,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserToken string `protobuf:"bytes,3,opt,name=user_token,json=userToken" json:"user_token,omitempty"`
}

func (m *UserTokenAuthReq) Reset()                    { *m = UserTokenAuthReq{} }
func (m *UserTokenAuthReq) String() string            { return proto.CompactTextString(m) }
func (*UserTokenAuthReq) ProtoMessage()               {}
func (*UserTokenAuthReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserTokenAuthReq) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *UserTokenAuthReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserTokenAuthReq) GetUserToken() string {
	if m != nil {
		return m.UserToken
	}
	return ""
}

// 服务器和客户端对时
type UserTokenAuthRsp struct {
	// uint64 client_time = 1;
	// uint64 server_time = 2;
	AppId  uint32 `protobuf:"varint,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Nick   string `protobuf:"bytes,3,opt,name=nick" json:"nick,omitempty"`
	Avatar string `protobuf:"bytes,4,opt,name=avatar" json:"avatar,omitempty"`
}

func (m *UserTokenAuthRsp) Reset()                    { *m = UserTokenAuthRsp{} }
func (m *UserTokenAuthRsp) String() string            { return proto.CompactTextString(m) }
func (*UserTokenAuthRsp) ProtoMessage()               {}
func (*UserTokenAuthRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserTokenAuthRsp) GetAppId() uint32 {
	if m != nil {
		return m.AppId
	}
	return 0
}

func (m *UserTokenAuthRsp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserTokenAuthRsp) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *UserTokenAuthRsp) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterType((*UserTokenAuthReq)(nil), "zproto.UserTokenAuthReq")
	proto.RegisterType((*UserTokenAuthRsp)(nil), "zproto.UserTokenAuthRsp")
}

func init() { proto.RegisterFile("auths.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2c, 0x2d, 0xc9,
	0x28, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xab, 0x02, 0xd3, 0x4a, 0xc9, 0x5c, 0x02,
	0xa1, 0xc5, 0xa9, 0x45, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x8e, 0xa5, 0x25, 0x19, 0x41, 0xa9, 0x85,
	0x42, 0xe2, 0x5c, 0xec, 0x89, 0x05, 0x05, 0xf1, 0xd9, 0xa9, 0x95, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x6c, 0x89, 0x05, 0x05, 0xde, 0xa9, 0x95, 0x20, 0x89, 0xd2, 0xe2, 0xd4, 0xa2, 0xf8,
	0xcc, 0x14, 0x09, 0x26, 0x88, 0x04, 0x88, 0xeb, 0x99, 0x22, 0x24, 0xcb, 0xc5, 0x05, 0x96, 0x28,
	0x01, 0x19, 0x23, 0xc1, 0x0c, 0x96, 0xe3, 0x2c, 0x85, 0x99, 0xab, 0x94, 0x87, 0x6e, 0x49, 0x71,
	0x81, 0x90, 0x28, 0x17, 0xc8, 0x54, 0x90, 0x51, 0x20, 0x3b, 0x78, 0x83, 0x58, 0x13, 0x0b, 0x0a,
	0x3c, 0x53, 0x70, 0x5b, 0x21, 0xc4, 0xc5, 0x92, 0x97, 0x99, 0x9c, 0x0d, 0x35, 0x1c, 0xcc, 0x16,
	0x12, 0xe3, 0x62, 0x4b, 0x2c, 0x4b, 0x2c, 0x49, 0x2c, 0x92, 0x60, 0x81, 0xba, 0x13, 0xcc, 0x73,
	0x52, 0xe6, 0x12, 0x4f, 0xce, 0xcf, 0xd5, 0xab, 0x4a, 0xce, 0x48, 0x2c, 0xd1, 0x4b, 0xcd, 0x4b,
	0xcf, 0xcc, 0x4b, 0xd5, 0x83, 0xf8, 0xd7, 0x89, 0x2d, 0x2a, 0x00, 0x44, 0x7b, 0x30, 0x25, 0xb1,
	0x81, 0x05, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x5b, 0xbe, 0x24, 0x17, 0x01, 0x00,
	0x00,
}
